package com.stc.pattysmorestuff.tools.init;

import com.stc.pattysmorestuff.lib.ConfigPreInit;
import com.stc.pattysmorestuff.tools.items.*;
import net.minecraft.client.renderer.block.model.ModelResourceLocation;
import net.minecraft.item.Item;
import net.minecraftforge.client.model.ModelLoader;
import net.minecraftforge.fml.common.registry.GameRegistry;

/**
 * Created by StuffTheChicken on 14/11/2016.
 */
public class ModDyeTools {

    public static Item white_pickaxe;
    public static Item white_axe;
    public static Item white_shovel;
    public static Item white_hoe;
    public static Item white_sword;
    public static Item orange_pickaxe;
    public static Item orange_axe;
    public static Item orange_shovel;
    public static Item orange_hoe;
    public static Item orange_sword;
    public static Item magenta_pickaxe;
    public static Item magenta_axe;
    public static Item magenta_shovel;
    public static Item magenta_hoe;
    public static Item magenta_sword;
    public static Item lightblue_pickaxe;
    public static Item lightblue_axe;
    public static Item lightblue_shovel;
    public static Item lightblue_hoe;
    public static Item lightblue_sword;
    public static Item yellow_pickaxe;
    public static Item yellow_axe;
    public static Item yellow_shovel;
    public static Item yellow_hoe;
    public static Item yellow_sword;
    public static Item lime_pickaxe;
    public static Item lime_axe;
    public static Item lime_shovel;
    public static Item lime_hoe;
    public static Item lime_sword;
    public static Item pink_pickaxe;
    public static Item pink_axe;
    public static Item pink_shovel;
    public static Item pink_hoe;
    public static Item pink_sword;
    public static Item gray_pickaxe;
    public static Item gray_axe;
    public static Item gray_shovel;
    public static Item gray_hoe;
    public static Item gray_sword;
    public static Item lightgray_pickaxe;
    public static Item lightgray_axe;
    public static Item lightgray_shovel;
    public static Item lightgray_hoe;
    public static Item lightgray_sword;
    public static Item cyan_pickaxe;
    public static Item cyan_axe;
    public static Item cyan_shovel;
    public static Item cyan_hoe;
    public static Item cyan_sword;
    public static Item purple_pickaxe;
    public static Item purple_axe;
    public static Item purple_shovel;
    public static Item purple_hoe;
    public static Item purple_sword;
    public static Item blue_pickaxe;
    public static Item blue_axe;
    public static Item blue_shovel;
    public static Item blue_hoe;
    public static Item blue_sword;
    public static Item brown_pickaxe;
    public static Item brown_axe;
    public static Item brown_shovel;
    public static Item brown_hoe;
    public static Item brown_sword;
    public static Item green_pickaxe;
    public static Item green_axe;
    public static Item green_shovel;
    public static Item green_hoe;
    public static Item green_sword;
    public static Item red_pickaxe;
    public static Item red_axe;
    public static Item red_shovel;
    public static Item red_hoe;
    public static Item red_sword;
    public static Item black_pickaxe;
    public static Item black_axe;
    public static Item black_shovel;
    public static Item black_hoe;
    public static Item black_sword;

    public static void init() {
        black_pickaxe = new ItemPick("black_pickaxe", ConfigPreInit.DYE_TOOL);
        black_axe = new ItemAx("black_axe", ConfigPreInit.DYE_TOOL);
        black_shovel = new ItemShovel("black_shovel", ConfigPreInit.DYE_TOOL);
        black_hoe = new ItemCustomHoe("black_hoe", ConfigPreInit.DYE_TOOL);
        black_sword = new ItemCustomSword("black_sword", ConfigPreInit.DYE_TOOL);
        red_pickaxe = new ItemPick("red_pickaxe", ConfigPreInit.DYE_TOOL);
        red_axe = new ItemAx("red_axe", ConfigPreInit.DYE_TOOL);
        red_shovel = new ItemShovel("red_shovel", ConfigPreInit.DYE_TOOL);
        red_hoe = new ItemCustomHoe("red_hoe", ConfigPreInit.DYE_TOOL);
        red_sword = new ItemCustomSword("red_sword", ConfigPreInit.DYE_TOOL);
        green_pickaxe = new ItemPick("green_pickaxe", ConfigPreInit.DYE_TOOL);
        green_axe = new ItemAx("green_axe", ConfigPreInit.DYE_TOOL);
        green_shovel = new ItemShovel("green_shovel", ConfigPreInit.DYE_TOOL);
        green_hoe = new ItemCustomHoe("green_hoe", ConfigPreInit.DYE_TOOL);
        green_sword = new ItemCustomSword("green_sword", ConfigPreInit.DYE_TOOL);
        brown_pickaxe = new ItemPick("brown_pickaxe", ConfigPreInit.DYE_TOOL);
        brown_axe = new ItemAx("brown_axe", ConfigPreInit.DYE_TOOL);
        brown_shovel = new ItemShovel("brown_shovel", ConfigPreInit.DYE_TOOL);
        brown_hoe = new ItemCustomHoe("brown_hoe", ConfigPreInit.DYE_TOOL);
        brown_sword = new ItemCustomSword("brown_sword", ConfigPreInit.DYE_TOOL);
        blue_pickaxe = new ItemPick("blue_pickaxe", ConfigPreInit.DYE_TOOL);
        blue_axe = new ItemAx("blue_axe", ConfigPreInit.DYE_TOOL);
        blue_shovel = new ItemShovel("blue_shovel", ConfigPreInit.DYE_TOOL);
        blue_hoe = new ItemCustomHoe("blue_hoe", ConfigPreInit.DYE_TOOL);
        blue_sword = new ItemCustomSword("blue_sword", ConfigPreInit.DYE_TOOL);
        purple_pickaxe = new ItemPick("purple_pickaxe", ConfigPreInit.DYE_TOOL);
        purple_axe = new ItemAx("purple_axe", ConfigPreInit.DYE_TOOL);
        purple_shovel = new ItemShovel("purple_shovel", ConfigPreInit.DYE_TOOL);
        purple_hoe = new ItemCustomHoe("purple_hoe", ConfigPreInit.DYE_TOOL);
        purple_sword = new ItemCustomSword("purple_sword", ConfigPreInit.DYE_TOOL);
        cyan_pickaxe = new ItemPick("cyan_pickaxe", ConfigPreInit.DYE_TOOL);
        cyan_axe = new ItemAx("cyan_axe", ConfigPreInit.DYE_TOOL);
        cyan_shovel = new ItemShovel("cyan_shovel", ConfigPreInit.DYE_TOOL);
        cyan_hoe = new ItemCustomHoe("cyan_hoe", ConfigPreInit.DYE_TOOL);
        cyan_sword = new ItemCustomSword("cyan_sword", ConfigPreInit.DYE_TOOL);
        lightgray_pickaxe = new ItemPick("lightgray_pickaxe", ConfigPreInit.DYE_TOOL);
        lightgray_axe = new ItemAx("lightgray_axe", ConfigPreInit.DYE_TOOL);
        lightgray_shovel = new ItemShovel("lightgray_shovel", ConfigPreInit.DYE_TOOL);
        lightgray_hoe = new ItemCustomHoe("lightgray_hoe", ConfigPreInit.DYE_TOOL);
        lightgray_sword = new ItemCustomSword("lightgray_sword", ConfigPreInit.DYE_TOOL);
        gray_pickaxe = new ItemPick("gray_pickaxe", ConfigPreInit.DYE_TOOL);
        gray_axe = new ItemAx("gray_axe", ConfigPreInit.DYE_TOOL);
        gray_shovel = new ItemShovel("gray_shovel", ConfigPreInit.DYE_TOOL);
        gray_hoe = new ItemCustomHoe("gray_hoe", ConfigPreInit.DYE_TOOL);
        gray_sword = new ItemCustomSword("gray_sword", ConfigPreInit.DYE_TOOL);
        pink_pickaxe = new ItemPick("pink_pickaxe", ConfigPreInit.DYE_TOOL);
        pink_axe = new ItemAx("pink_axe", ConfigPreInit.DYE_TOOL);
        pink_shovel = new ItemShovel("pink_shovel", ConfigPreInit.DYE_TOOL);
        pink_hoe = new ItemCustomHoe("pink_hoe", ConfigPreInit.DYE_TOOL);
        pink_sword = new ItemCustomSword("pink_sword", ConfigPreInit.DYE_TOOL);
        lime_pickaxe = new ItemPick("lime_pickaxe", ConfigPreInit.DYE_TOOL);
        lime_axe = new ItemAx("lime_axe", ConfigPreInit.DYE_TOOL);
        lime_shovel = new ItemShovel("lime_shovel", ConfigPreInit.DYE_TOOL);
        lime_hoe = new ItemCustomHoe("lime_hoe", ConfigPreInit.DYE_TOOL);
        lime_sword = new ItemCustomSword("lime_sword", ConfigPreInit.DYE_TOOL);
        yellow_pickaxe = new ItemPick("yellow_pickaxe", ConfigPreInit.DYE_TOOL);
        yellow_axe = new ItemAx("yellow_axe", ConfigPreInit.DYE_TOOL);
        yellow_shovel = new ItemShovel("yellow_shovel", ConfigPreInit.DYE_TOOL);
        yellow_hoe = new ItemCustomHoe("yellow_hoe", ConfigPreInit.DYE_TOOL);
        yellow_sword = new ItemCustomSword("yellow_sword", ConfigPreInit.DYE_TOOL);
        lightblue_pickaxe = new ItemPick("lightblue_pickaxe", ConfigPreInit.DYE_TOOL);
        lightblue_axe = new ItemAx("lightblue_axe", ConfigPreInit.DYE_TOOL);
        lightblue_shovel = new ItemShovel("lightblue_shovel", ConfigPreInit.DYE_TOOL);
        lightblue_hoe = new ItemCustomHoe("lightblue_hoe", ConfigPreInit.DYE_TOOL);
        lightblue_sword = new ItemCustomSword("lightblue_sword", ConfigPreInit.DYE_TOOL);
        magenta_pickaxe = new ItemPick("magenta_pickaxe", ConfigPreInit.DYE_TOOL);
        magenta_axe = new ItemAx("magenta_axe", ConfigPreInit.DYE_TOOL);
        magenta_shovel = new ItemShovel("magenta_shovel", ConfigPreInit.DYE_TOOL);
        magenta_hoe = new ItemCustomHoe("magenta_hoe", ConfigPreInit.DYE_TOOL);
        magenta_sword = new ItemCustomSword("magenta_sword", ConfigPreInit.DYE_TOOL);
        orange_pickaxe = new ItemPick("orange_pickaxe", ConfigPreInit.DYE_TOOL);
        orange_axe = new ItemAx("orange_axe", ConfigPreInit.DYE_TOOL);
        orange_shovel = new ItemShovel("orange_shovel", ConfigPreInit.DYE_TOOL);
        orange_hoe = new ItemCustomHoe("orange_hoe", ConfigPreInit.DYE_TOOL);
        orange_sword = new ItemCustomSword("orange_sword", ConfigPreInit.DYE_TOOL);
        white_pickaxe = new ItemPick("white_pickaxe", ConfigPreInit.DYE_TOOL);
        white_axe = new ItemAx("white_axe", ConfigPreInit.DYE_TOOL);
        white_shovel = new ItemShovel("white_shovel", ConfigPreInit.DYE_TOOL);
        white_hoe = new ItemCustomHoe("white_hoe", ConfigPreInit.DYE_TOOL);
        white_sword = new ItemCustomSword("white_sword", ConfigPreInit.DYE_TOOL);
        register(black_pickaxe);
        register(black_axe);
        register(black_shovel);
        register(black_hoe);
        register(black_sword);
        register(red_pickaxe);
        register(red_axe);
        register(red_shovel);
        register(red_hoe);
        register(red_sword);
        register(green_pickaxe);
        register(green_axe);
        register(green_shovel);
        register(green_hoe);
        register(green_sword);
        register(brown_pickaxe);
        register(brown_axe);
        register(brown_shovel);
        register(brown_hoe);
        register(brown_sword);
        register(blue_pickaxe);
        register(blue_axe);
        register(blue_shovel);
        register(blue_hoe);
        register(blue_sword);
        register(purple_pickaxe);
        register(purple_axe);
        register(purple_shovel);
        register(purple_hoe);
        register(purple_sword);
        register(cyan_pickaxe);
        register(cyan_axe);
        register(cyan_shovel);
        register(cyan_hoe);
        register(cyan_sword);
        register(lightgray_pickaxe);
        register(lightgray_axe);
        register(lightgray_shovel);
        register(lightgray_hoe);
        register(lightgray_sword);
        register(gray_pickaxe);
        register(gray_axe);
        register(gray_shovel);
        register(gray_hoe);
        register(gray_sword);
        register(pink_pickaxe);
        register(pink_axe);
        register(pink_shovel);
        register(pink_hoe);
        register(pink_sword);
        register(lime_pickaxe);
        register(lime_axe);
        register(lime_shovel);
        register(lime_hoe);
        register(lime_sword);
        register(yellow_pickaxe);
        register(yellow_axe);
        register(yellow_shovel);
        register(yellow_hoe);
        register(yellow_sword);
        register(lightblue_pickaxe);
        register(lightblue_axe);
        register(lightblue_shovel);
        register(lightblue_hoe);
        register(lightblue_sword);
        register(magenta_pickaxe);
        register(magenta_axe);
        register(magenta_shovel);
        register(magenta_hoe);
        register(magenta_sword);
        register(orange_pickaxe);
        register(orange_axe);
        register(orange_shovel);
        register(orange_hoe);
        register(orange_sword);
        register(white_pickaxe);
        register(white_axe);
        register(white_shovel);
        register(white_hoe);
        register(white_sword);
    }

    public static void register(Item item) {
        GameRegistry.register(item);
    }

    public static void registerRenders() {
        registerRender(white_pickaxe);
        registerRender(white_axe);
        registerRender(white_shovel);
        registerRender(white_hoe);
        registerRender(white_sword);
        registerRender(orange_pickaxe);
        registerRender(orange_axe);
        registerRender(orange_shovel);
        registerRender(orange_hoe);
        registerRender(orange_sword);
        registerRender(magenta_pickaxe);
        registerRender(magenta_axe);
        registerRender(magenta_shovel);
        registerRender(magenta_hoe);
        registerRender(magenta_sword);
        registerRender(lightblue_pickaxe);
        registerRender(lightblue_axe);
        registerRender(lightblue_shovel);
        registerRender(lightblue_hoe);
        registerRender(lightblue_sword);
        registerRender(yellow_pickaxe);
        registerRender(yellow_axe);
        registerRender(yellow_shovel);
        registerRender(yellow_hoe);
        registerRender(yellow_sword);
        registerRender(lime_pickaxe);
        registerRender(lime_axe);
        registerRender(lime_shovel);
        registerRender(lime_hoe);
        registerRender(lime_sword);
        registerRender(pink_pickaxe);
        registerRender(pink_axe);
        registerRender(pink_shovel);
        registerRender(pink_hoe);
        registerRender(pink_sword);
        registerRender(gray_pickaxe);
        registerRender(gray_axe);
        registerRender(gray_shovel);
        registerRender(gray_hoe);
        registerRender(gray_sword);
        registerRender(lightgray_pickaxe);
        registerRender(lightgray_axe);
        registerRender(lightgray_shovel);
        registerRender(lightgray_hoe);
        registerRender(lightgray_sword);
        registerRender(cyan_pickaxe);
        registerRender(cyan_axe);
        registerRender(cyan_shovel);
        registerRender(cyan_hoe);
        registerRender(cyan_sword);
        registerRender(purple_pickaxe);
        registerRender(purple_axe);
        registerRender(purple_shovel);
        registerRender(purple_hoe);
        registerRender(purple_sword);
        registerRender(blue_pickaxe);
        registerRender(blue_axe);
        registerRender(blue_shovel);
        registerRender(blue_hoe);
        registerRender(blue_sword);
        registerRender(brown_pickaxe);
        registerRender(brown_axe);
        registerRender(brown_shovel);
        registerRender(brown_hoe);
        registerRender(brown_sword);
        registerRender(green_pickaxe);
        registerRender(green_axe);
        registerRender(green_shovel);
        registerRender(green_hoe);
        registerRender(green_sword);
        registerRender(red_pickaxe);
        registerRender(red_axe);
        registerRender(red_shovel);
        registerRender(red_hoe);
        registerRender(red_sword);
        registerRender(black_pickaxe);
        registerRender(black_axe);
        registerRender(black_shovel);
        registerRender(black_hoe);
        registerRender(black_sword);
    }

    private static void registerRender(Item item) {
        ModelResourceLocation modResLoc = new ModelResourceLocation(item.getRegistryName().toString(), "inventory");
        ModelLoader.setCustomModelResourceLocation(item, 0, modResLoc);
    }
}
