package com.stc.pattysmorestuff.crafting;

import com.stc.pattysmorestuff.ConfigPreInit;
import com.stc.pattysmorestuff.ModPMS;
import com.stc.pattysmorestuff.PattysMoreStuff;
import com.stc.pattysmorestuff.armor.init.ModArmor;
import com.stc.pattysmorestuff.armor.init.ModDyeArmor;
import com.stc.pattysmorestuff.blocks.ModBlocks;
import com.stc.pattysmorestuff.food.init.ModFood;
import com.stc.pattysmorestuff.furnaces.init.ModFurnaces;
import com.stc.pattysmorestuff.random.init.ModRandomItems;
import com.stc.pattysmorestuff.tools.init.*;
import net.minecraft.entity.EntityList;
import net.minecraft.entity.passive.EntityPig;
import net.minecraft.init.Blocks;
import net.minecraft.init.Items;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;
import net.minecraftforge.common.MinecraftForge;
import net.minecraftforge.fml.common.registry.GameRegistry;
import scala.util.Random;

/**
 * Created by peeweebirch70 on 11/11/2016.
 */
public class ModCrafting {

    public static void recipes() {

        if (ConfigPreInit.disableTools) {

            //Pattys Battleaxes
            GameRegistry.addRecipe(new ItemStack(ModTools.wooden_battle_axe, 1), new Object[]{"III", "ISI", " S ", 'I', Blocks.PLANKS, 'S', Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.stone_battle_axe, 1), new Object[]{"III", "ISI", " S ", 'I', Blocks.COBBLESTONE, 'S', Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.iron_battle_axe, 1), new Object[]{"III", "ISI", " S ", 'I', Items.IRON_INGOT, 'S', Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.gold_battle_axe, 1), new Object[]{"III", "ISI", " S ", 'I', Items.GOLD_INGOT, 'S', Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.diamond_battle_axe, 1), new Object[]{"III", "ISI", " S ", 'I', Items.DIAMOND, 'S', Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.netherstar_battle_axe, 1), new Object[]{"III", "ISI", " S ", 'I', Items.NETHER_STAR, 'S', Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.obsidian_battle_axe, 1), new Object[]{"III", "ISI", " S ", 'I', ModPMS.obsidian_ingot, 'S', Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.emerald_battle_axe, 1), new Object[]{"III", "ISI", " S ", 'I', Items.EMERALD, 'S', Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.ender_battle_axe, 1), new Object[]{"III", "ISI", " S ", 'I', Items.ENDER_PEARL, 'S', Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.quartz_battle_axe, 1), new Object[]{"III", "ISI", " S ", 'I', Items.QUARTZ, 'S', Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.blaze_battle_axe, 1), new Object[]{"III", "ISI", " S ", 'I', Items.BLAZE_POWDER, 'S', Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.flint_battle_axe, 1), new Object[]{"III", "ISI", " S ", 'I', Items.FLINT, 'S', Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.coal_battle_axe, 1), new Object[]{"III", "ISI", " S ", 'I', Items.COAL, 'S', Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.gunpowder_battle_axe, 1), new Object[]{"III", "ISI", " S ", 'I', Items.GUNPOWDER, 'S', Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.redstone_battle_axe, 1), new Object[]{"III", "ISI", " S ", 'I', Items.REDSTONE, 'S', Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.glowstone_battle_axe, 1), new Object[]{"III", "ISI", " S ", 'I', Items.GLOWSTONE_DUST, 'S', Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.snow_battle_axe, 1), new Object[]{"III", "ISI", " S ", 'I', Items.SNOWBALL, 'S', Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.brick_battle_axe, 1), new Object[]{"III", "ISI", " S ", 'I', Items.BRICK, 'S', Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.netherbrick_battle_axe, 1), new Object[]{"III", "ISI", " S ", 'I', Items.NETHERBRICK, 'S', Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.leather_battle_axe, 1), new Object[]{"III", "ISI", " S ", 'I', Items.LEATHER, 'S', Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.slime_battle_axe, 1), new Object[]{"III", "ISI", " S ", 'I', Items.SLIME_BALL, 'S', Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.clay_battle_axe, 1), new Object[]{"III", "ISI", " S ", 'I', Items.CLAY_BALL, 'S', Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.sandstone_battle_axe, 1), new Object[]{"III", "ISI", " S ", 'I', Blocks.SANDSTONE, 'S', Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.soulsand_battle_axe, 1), new Object[]{"III", "ISI", " S ", 'I', Blocks.SOUL_SAND, 'S', Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.magmacream_battle_axe, 1), new Object[]{"III", "ISI", " S ", 'I', Items.MAGMA_CREAM, 'S', Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.netherbrickred_battle_axe, 1), new Object[]{"III", "ISI", " S ", 'I', Blocks.RED_NETHER_BRICK, 'S', Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModDyeToolBattleaxe.black_battle_axe, 1), new Object[]{"III", "ISI", " S ", Character.valueOf('I'), new ItemStack(Items.DYE, 1, 0), 'S', Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModDyeToolBattleaxe.red_battle_axe, 1), new Object[]{"III", "ISI", " S ", Character.valueOf('I'), new ItemStack(Items.DYE, 1, 1), 'S', Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModDyeToolBattleaxe.green_battle_axe, 1), new Object[]{"III", "ISI", " S ", Character.valueOf('I'), new ItemStack(Items.DYE, 1, 2), 'S', Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModDyeToolBattleaxe.brown_battle_axe, 1), new Object[]{"III", "ISI", " S ", Character.valueOf('I'), new ItemStack(Items.DYE, 1, 3), 'S', Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModDyeToolBattleaxe.blue_battle_axe, 1), new Object[]{"III", "ISI", " S ", Character.valueOf('I'), new ItemStack(Items.DYE, 1, 4), 'S', Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModDyeToolBattleaxe.purple_battle_axe, 1), new Object[]{"III", "ISI", " S ", Character.valueOf('I'), new ItemStack(Items.DYE, 1, 5), 'S', Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModDyeToolBattleaxe.cyan_battle_axe, 1), new Object[]{"III", "ISI", " S ", Character.valueOf('I'), new ItemStack(Items.DYE, 1, 6), 'S', Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModDyeToolBattleaxe.lightgray_battle_axe, 1), new Object[]{"III", "ISI", " S ", Character.valueOf('I'), new ItemStack(Items.DYE, 1, 7), 'S', Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModDyeToolBattleaxe.gray_battle_axe, 1), new Object[]{"III", "ISI", " S ", Character.valueOf('I'), new ItemStack(Items.DYE, 1, 8), 'S', Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModDyeToolBattleaxe.pink_battle_axe, 1), new Object[]{"III", "ISI", " S ", Character.valueOf('I'), new ItemStack(Items.DYE, 1, 9), 'S', Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModDyeToolBattleaxe.lime_battle_axe, 1), new Object[]{"III", "ISI", " S ", Character.valueOf('I'), new ItemStack(Items.DYE, 1, 10), 'S', Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModDyeToolBattleaxe.yellow_battle_axe, 1), new Object[]{"III", "ISI", " S ", Character.valueOf('I'), new ItemStack(Items.DYE, 1, 11), 'S', Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModDyeToolBattleaxe.lightblue_battle_axe, 1), new Object[]{"III", "ISI", " S ", Character.valueOf('I'), new ItemStack(Items.DYE, 1, 12), 'S', Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModDyeToolBattleaxe.magenta_battle_axe, 1), new Object[]{"III", "ISI", " S ", Character.valueOf('I'), new ItemStack(Items.DYE, 1, 13), 'S', Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModDyeToolBattleaxe.orange_battle_axe, 1), new Object[]{"III", "ISI", " S ", Character.valueOf('I'), new ItemStack(Items.DYE, 1, 14), 'S', Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModDyeToolBattleaxe.white_battle_axe, 1), new Object[]{"III", "ISI", " S ", Character.valueOf('I'), new ItemStack(Items.DYE, 1, 15), 'S', Items.STICK});

            //PattysMoreTools
            GameRegistry.addRecipe(new ItemStack(ModTools.emerald_pickaxe, 1), new Object[]{"CCC", " S ", " S ", Character.valueOf('C'), Items.EMERALD, Character.valueOf('S'), Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.emerald_axe, 1), new Object[]{" CC", " SC", " S ", Character.valueOf('C'), Items.EMERALD, Character.valueOf('S'), Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.emerald_shovel, 1), new Object[]{" C ", " S ", " S ", Character.valueOf('C'), Items.EMERALD, Character.valueOf('S'), Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.emerald_hoe, 1), new Object[]{" CC", " S ", " S ", Character.valueOf('C'), Items.EMERALD, Character.valueOf('S'), Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.emerald_sword, 1), new Object[]{" C ", " C ", " S ", Character.valueOf('C'), Items.EMERALD, Character.valueOf('S'), Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.obsidian_pickaxe, 1), new Object[]{"CCC", " S ", " S ", Character.valueOf('C'), ModPMS.obsidian_ingot, Character.valueOf('S'), Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.obsidian_axe, 1), new Object[]{" CC", " SC", " S ", Character.valueOf('C'), ModPMS.obsidian_ingot, Character.valueOf('S'), Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.obsidian_shovel, 1), new Object[]{" C ", " S ", " S ", Character.valueOf('C'), ModPMS.obsidian_ingot, Character.valueOf('S'), Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.obsidian_hoe, 1), new Object[]{" CC", " S ", " S ", Character.valueOf('C'), ModPMS.obsidian_ingot, Character.valueOf('S'), Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.obsidian_sword, 1), new Object[]{" C ", " C ", " S ", Character.valueOf('C'), ModPMS.obsidian_ingot, Character.valueOf('S'), Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.slime_pickaxe, 1), new Object[]{"CCC", " S ", " S ", Character.valueOf('C'), Items.SLIME_BALL, Character.valueOf('S'), Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.slime_axe, 1), new Object[]{" CC", " SC", " S ", Character.valueOf('C'), Items.SLIME_BALL, Character.valueOf('S'), Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.slime_shovel, 1), new Object[]{" C ", " S ", " S ", Character.valueOf('C'), Items.SLIME_BALL, Character.valueOf('S'), Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.slime_hoe, 1), new Object[]{" CC", " S ", " S ", Character.valueOf('C'), Items.SLIME_BALL, Character.valueOf('S'), Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.slime_sword, 1), new Object[]{" C ", " C ", " S ", Character.valueOf('C'), Items.SLIME_BALL, Character.valueOf('S'), Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.coal_pickaxe, 1), new Object[]{"CCC", " S ", " S ", Character.valueOf('C'), Items.COAL, Character.valueOf('S'), Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.coal_axe, 1), new Object[]{" CC", " SC", " S ", Character.valueOf('C'), Items.COAL, Character.valueOf('S'), Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.coal_shovel, 1), new Object[]{" C ", " S ", " S ", Character.valueOf('C'), Items.COAL, Character.valueOf('S'), Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.coal_hoe, 1), new Object[]{" CC", " S ", " S ", Character.valueOf('C'), Items.COAL, Character.valueOf('S'), Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.coal_sword, 1), new Object[]{" C ", " C ", " S ", Character.valueOf('C'), Items.COAL, Character.valueOf('S'), Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.coal_pickaxe, 1), new Object[]{"CCC", " S ", " S ", Character.valueOf('C'), new ItemStack(Items.COAL, 1, 1), Character.valueOf('S'), Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.coal_axe, 1), new Object[]{" CC", " SC", " S ", Character.valueOf('C'), new ItemStack(Items.COAL, 1, 1), Character.valueOf('S'), Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.coal_shovel, 1), new Object[]{" C ", " S ", " S ", Character.valueOf('C'), new ItemStack(Items.COAL, 1, 1), Character.valueOf('S'), Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.coal_hoe, 1), new Object[]{" CC", " S ", " S ", Character.valueOf('C'), new ItemStack(Items.COAL, 1, 1), Character.valueOf('S'), Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.coal_sword, 1), new Object[]{" C ", " C ", " S ", Character.valueOf('C'), new ItemStack(Items.COAL, 1, 1), Character.valueOf('S'), Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.flint_pickaxe, 1), new Object[]{"CCC", " S ", " S ", Character.valueOf('C'), Items.FLINT, Character.valueOf('S'), Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.flint_axe, 1), new Object[]{" CC", " SC", " S ", Character.valueOf('C'), Items.FLINT, Character.valueOf('S'), Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.flint_shovel, 1), new Object[]{" C ", " S ", " S ", Character.valueOf('C'), Items.FLINT, Character.valueOf('S'), Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.flint_hoe, 1), new Object[]{" CC", " S ", " S ", Character.valueOf('C'), Items.FLINT, Character.valueOf('S'), Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.flint_sword, 1), new Object[]{" C ", " C ", " S ", Character.valueOf('C'), Items.FLINT, Character.valueOf('S'), Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.leather_pickaxe, 1), new Object[]{"CCC", " S ", " S ", Character.valueOf('C'), Items.LEATHER, Character.valueOf('S'), Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.leather_axe, 1), new Object[]{" CC", " SC", " S ", Character.valueOf('C'), Items.LEATHER, Character.valueOf('S'), Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.leather_shovel, 1), new Object[]{" C ", " S ", " S ", Character.valueOf('C'), Items.LEATHER, Character.valueOf('S'), Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.leather_hoe, 1), new Object[]{" CC", " S ", " S ", Character.valueOf('C'), Items.LEATHER, Character.valueOf('S'), Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.leather_sword, 1), new Object[]{" C ", " C ", " S ", Character.valueOf('C'), Items.LEATHER, Character.valueOf('S'), Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.glowstone_pickaxe, 1), new Object[]{"CCC", " S ", " S ", Character.valueOf('C'), Items.GLOWSTONE_DUST, Character.valueOf('S'), Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.glowstone_axe, 1), new Object[]{" CC", " SC", " S ", Character.valueOf('C'), Items.GLOWSTONE_DUST, Character.valueOf('S'), Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.glowstone_shovel, 1), new Object[]{" C ", " S ", " S ", Character.valueOf('C'), Items.GLOWSTONE_DUST, Character.valueOf('S'), Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.glowstone_hoe, 1), new Object[]{" CC", " S ", " S ", Character.valueOf('C'), Items.GLOWSTONE_DUST, Character.valueOf('S'), Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.glowstone_sword, 1), new Object[]{" C ", " C ", " S ", Character.valueOf('C'), Items.GLOWSTONE_DUST, Character.valueOf('S'), Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.gunpowder_pickaxe, 1), new Object[]{"CCC", " S ", " S ", Character.valueOf('C'), Items.GUNPOWDER, Character.valueOf('S'), Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.gunpowder_axe, 1), new Object[]{" CC", " SC", " S ", Character.valueOf('C'), Items.GUNPOWDER, Character.valueOf('S'), Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.gunpowder_shovel, 1), new Object[]{" C ", " S ", " S ", Character.valueOf('C'), Items.GUNPOWDER, Character.valueOf('S'), Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.gunpowder_hoe, 1), new Object[]{" CC", " S ", " S ", Character.valueOf('C'), Items.GUNPOWDER, Character.valueOf('S'), Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.gunpowder_sword, 1), new Object[]{" C ", " C ", " S ", Character.valueOf('C'), Items.GUNPOWDER, Character.valueOf('S'), Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.quartz_pickaxe, 1), new Object[]{"CCC", " S ", " S ", Character.valueOf('C'), Items.QUARTZ, Character.valueOf('S'), Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.quartz_axe, 1), new Object[]{" CC", " SC", " S ", Character.valueOf('C'), Items.QUARTZ, Character.valueOf('S'), Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.quartz_shovel, 1), new Object[]{" C ", " S ", " S ", Character.valueOf('C'), Items.QUARTZ, Character.valueOf('S'), Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.quartz_hoe, 1), new Object[]{" CC", " S ", " S ", Character.valueOf('C'), Items.QUARTZ, Character.valueOf('S'), Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.quartz_sword, 1), new Object[]{" C ", " C ", " S ", Character.valueOf('C'), Items.QUARTZ, Character.valueOf('S'), Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.redstone_pickaxe, 1), new Object[]{"CCC", " S ", " S ", Character.valueOf('C'), Items.REDSTONE, Character.valueOf('S'), Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.redstone_axe, 1), new Object[]{" CC", " SC", " S ", Character.valueOf('C'), Items.REDSTONE, Character.valueOf('S'), Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.redstone_shovel, 1), new Object[]{" C ", " S ", " S ", Character.valueOf('C'), Items.REDSTONE, Character.valueOf('S'), Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.redstone_hoe, 1), new Object[]{" CC", " S ", " S ", Character.valueOf('C'), Items.REDSTONE, Character.valueOf('S'), Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.redstone_sword, 1), new Object[]{" C ", " C ", " S ", Character.valueOf('C'), Items.REDSTONE, Character.valueOf('S'), Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.nbrick_pickaxe, 1), new Object[]{"CCC", " S ", " S ", Character.valueOf('C'), Items.NETHERBRICK, Character.valueOf('S'), Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.nbrick_axe, 1), new Object[]{" CC", " SC", " S ", Character.valueOf('C'), Items.NETHERBRICK, Character.valueOf('S'), Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.nbrick_shovel, 1), new Object[]{" C ", " S ", " S ", Character.valueOf('C'), Items.NETHERBRICK, Character.valueOf('S'), Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.nbrick_hoe, 1), new Object[]{" CC", " S ", " S ", Character.valueOf('C'), Items.NETHERBRICK, Character.valueOf('S'), Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.nbrick_sword, 1), new Object[]{" C ", " C ", " S ", Character.valueOf('C'), Items.NETHERBRICK, Character.valueOf('S'), Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.brick_pickaxe, 1), new Object[]{"CCC", " S ", " S ", Character.valueOf('C'), Items.BRICK, Character.valueOf('S'), Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.brick_axe, 1), new Object[]{" CC", " SC", " S ", Character.valueOf('C'), Items.BRICK, Character.valueOf('S'), Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.brick_shovel, 1), new Object[]{" C ", " S ", " S ", Character.valueOf('C'), Items.BRICK, Character.valueOf('S'), Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.brick_hoe, 1), new Object[]{" CC", " S ", " S ", Character.valueOf('C'), Items.BRICK, Character.valueOf('S'), Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.brick_sword, 1), new Object[]{" C ", " C ", " S ", Character.valueOf('C'), Items.BRICK, Character.valueOf('S'), Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.blaze_pickaxe, 1), new Object[]{"CCC", " S ", " S ", Character.valueOf('C'), Items.BLAZE_POWDER, Character.valueOf('S'), Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.blaze_axe, 1), new Object[]{" CC", " SC", " S ", Character.valueOf('C'), Items.BLAZE_POWDER, Character.valueOf('S'), Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.blaze_shovel, 1), new Object[]{" C ", " S ", " S ", Character.valueOf('C'), Items.BLAZE_POWDER, Character.valueOf('S'), Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.blaze_hoe, 1), new Object[]{" CC", " S ", " S ", Character.valueOf('C'), Items.BLAZE_POWDER, Character.valueOf('S'), Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.blaze_sword, 1), new Object[]{" C ", " C ", " S ", Character.valueOf('C'), Items.BLAZE_POWDER, Character.valueOf('S'), Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.nstar_pickaxe, 1), new Object[]{"CCC", " S ", " S ", Character.valueOf('C'), Items.NETHER_STAR, Character.valueOf('S'), Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.nstar_axe, 1), new Object[]{" CC", " SC", " S ", Character.valueOf('C'), Items.NETHER_STAR, Character.valueOf('S'), Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.nstar_shovel, 1), new Object[]{" C ", " S ", " S ", Character.valueOf('C'), Items.NETHER_STAR, Character.valueOf('S'), Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.nstar_hoe, 1), new Object[]{" CC", " S ", " S ", Character.valueOf('C'), Items.NETHER_STAR, Character.valueOf('S'), Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.nstar_sword, 1), new Object[]{" C ", " C ", " S ", Character.valueOf('C'), Items.NETHER_STAR, Character.valueOf('S'), Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.snow_pickaxe, 1), new Object[]{"CCC", " S ", " S ", Character.valueOf('C'), Items.SNOWBALL, Character.valueOf('S'), Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.snow_axe, 1), new Object[]{" CC", " SC", " S ", Character.valueOf('C'), Items.SNOWBALL, Character.valueOf('S'), Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.snow_shovel, 1), new Object[]{" C ", " S ", " S ", Character.valueOf('C'), Items.SNOWBALL, Character.valueOf('S'), Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.snow_hoe, 1), new Object[]{" CC", " S ", " S ", Character.valueOf('C'), Items.SNOWBALL, Character.valueOf('S'), Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.snow_sword, 1), new Object[]{" C ", " C ", " S ", Character.valueOf('C'), Items.SNOWBALL, Character.valueOf('S'), Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.ender_pickaxe, 1), new Object[]{"CCC", " S ", " S ", Character.valueOf('C'), Items.ENDER_PEARL, Character.valueOf('S'), Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.ender_axe, 1), new Object[]{" CC", " SC", " S ", Character.valueOf('C'), Items.ENDER_PEARL, Character.valueOf('S'), Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.ender_shovel, 1), new Object[]{" C ", " S ", " S ", Character.valueOf('C'), Items.ENDER_PEARL, Character.valueOf('S'), Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.ender_hoe, 1), new Object[]{" CC", " S ", " S ", Character.valueOf('C'), Items.ENDER_PEARL, Character.valueOf('S'), Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.ender_sword, 1), new Object[]{" C ", " C ", " S ", Character.valueOf('C'), Items.ENDER_PEARL, Character.valueOf('S'), Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.magma_cream_pickaxe, 1), new Object[]{"CCC", " S ", " S ", Character.valueOf('C'), Items.MAGMA_CREAM, Character.valueOf('S'), Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.magma_cream_axe, 1), new Object[]{" CC", " SC", " S ", Character.valueOf('C'), Items.MAGMA_CREAM, Character.valueOf('S'), Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.magma_cream_shovel, 1), new Object[]{" C ", " S ", " S ", Character.valueOf('C'), Items.MAGMA_CREAM, Character.valueOf('S'), Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.magma_cream_hoe, 1), new Object[]{" CC", " S ", " S ", Character.valueOf('C'), Items.MAGMA_CREAM, Character.valueOf('S'), Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.magma_cream_sword, 1), new Object[]{" C ", " C ", " S ", Character.valueOf('C'), Items.MAGMA_CREAM, Character.valueOf('S'), Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.sandstone_pickaxe, 1), new Object[]{"CCC", " S ", " S ", Character.valueOf('C'), Blocks.SANDSTONE, Character.valueOf('S'), Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.sandstone_axe, 1), new Object[]{" CC", " SC", " S ", Character.valueOf('C'), Blocks.SANDSTONE, Character.valueOf('S'), Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.sandstone_shovel, 1), new Object[]{" C ", " S ", " S ", Character.valueOf('C'), Blocks.SANDSTONE, Character.valueOf('S'), Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.sandstone_hoe, 1), new Object[]{" CC", " S ", " S ", Character.valueOf('C'), Blocks.SANDSTONE, Character.valueOf('S'), Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.sandstone_sword, 1), new Object[]{" C ", " C ", " S ", Character.valueOf('C'), Blocks.SANDSTONE, Character.valueOf('S'), Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.soul_sand_pickaxe, 1), new Object[]{"CCC", " S ", " S ", Character.valueOf('C'), Blocks.SOUL_SAND, Character.valueOf('S'), Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.soul_sand_axe, 1), new Object[]{" CC", " SC", " S ", Character.valueOf('C'), Blocks.SOUL_SAND, Character.valueOf('S'), Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.soul_sand_shovel, 1), new Object[]{" C ", " S ", " S ", Character.valueOf('C'), Blocks.SOUL_SAND, Character.valueOf('S'), Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.soul_sand_hoe, 1), new Object[]{" CC", " S ", " S ", Character.valueOf('C'), Blocks.SOUL_SAND, Character.valueOf('S'), Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.soul_sand_sword, 1), new Object[]{" C ", " C ", " S ", Character.valueOf('C'), Blocks.SOUL_SAND, Character.valueOf('S'), Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.clay_pickaxe, 1), new Object[]{"CCC", " S ", " S ", Character.valueOf('C'), Items.CLAY_BALL, Character.valueOf('S'), Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.clay_axe, 1), new Object[]{" CC", " SC", " S ", Character.valueOf('C'), Items.CLAY_BALL, Character.valueOf('S'), Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.clay_shovel, 1), new Object[]{" C ", " S ", " S ", Character.valueOf('C'), Items.CLAY_BALL, Character.valueOf('S'), Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.clay_hoe, 1), new Object[]{" CC", " S ", " S ", Character.valueOf('C'), Items.CLAY_BALL, Character.valueOf('S'), Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.clay_sword, 1), new Object[]{" C ", " C ", " S ", Character.valueOf('C'), Items.CLAY_BALL, Character.valueOf('S'), Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModDyeTools.white_pickaxe, 1), new Object[]{"CCC", " S ", " S ", Character.valueOf('S'), Items.STICK, Character.valueOf('C'), new ItemStack(Items.DYE, 1, 15)});
            GameRegistry.addRecipe(new ItemStack(ModDyeTools.white_axe, 1), new Object[]{" CC", " SC", " S ", Character.valueOf('S'), Items.STICK, Character.valueOf('C'), new ItemStack(Items.DYE, 1, 15)});
            GameRegistry.addRecipe(new ItemStack(ModDyeTools.white_shovel, 1), new Object[]{" C ", " S ", " S ", Character.valueOf('S'), Items.STICK, Character.valueOf('C'), new ItemStack(Items.DYE, 1, 15)});
            GameRegistry.addRecipe(new ItemStack(ModDyeTools.white_hoe, 1), new Object[]{" CC", " S ", " S ", Character.valueOf('S'), Items.STICK, Character.valueOf('C'), new ItemStack(Items.DYE, 1, 15)});
            GameRegistry.addRecipe(new ItemStack(ModDyeTools.white_sword, 1), new Object[]{" C ", " C ", " S ", Character.valueOf('S'), Items.STICK, Character.valueOf('C'), new ItemStack(Items.DYE, 1, 15)});
            GameRegistry.addRecipe(new ItemStack(ModDyeTools.orange_pickaxe, 1), new Object[]{"CCC", " S ", " S ", Character.valueOf('S'), Items.STICK, Character.valueOf('C'), new ItemStack(Items.DYE, 1, 14)});
            GameRegistry.addRecipe(new ItemStack(ModDyeTools.orange_axe, 1), new Object[]{" CC", " SC", " S ", Character.valueOf('S'), Items.STICK, Character.valueOf('C'), new ItemStack(Items.DYE, 1, 14)});
            GameRegistry.addRecipe(new ItemStack(ModDyeTools.orange_shovel, 1), new Object[]{" C ", " S ", " S ", Character.valueOf('S'), Items.STICK, Character.valueOf('C'), new ItemStack(Items.DYE, 1, 14)});
            GameRegistry.addRecipe(new ItemStack(ModDyeTools.orange_hoe, 1), new Object[]{" CC", " S ", " S ", Character.valueOf('S'), Items.STICK, Character.valueOf('C'), new ItemStack(Items.DYE, 1, 14)});
            GameRegistry.addRecipe(new ItemStack(ModDyeTools.orange_sword, 1), new Object[]{" C ", " C ", " S ", Character.valueOf('S'), Items.STICK, Character.valueOf('C'), new ItemStack(Items.DYE, 1, 14)});
            GameRegistry.addRecipe(new ItemStack(ModDyeTools.magenta_pickaxe, 1), new Object[]{"CCC", " S ", " S ", Character.valueOf('S'), Items.STICK, Character.valueOf('C'), new ItemStack(Items.DYE, 1, 13)});
            GameRegistry.addRecipe(new ItemStack(ModDyeTools.magenta_axe, 1), new Object[]{" CC", " SC", " S ", Character.valueOf('S'), Items.STICK, Character.valueOf('C'), new ItemStack(Items.DYE, 1, 13)});
            GameRegistry.addRecipe(new ItemStack(ModDyeTools.magenta_shovel, 1), new Object[]{" C ", " S ", " S ", Character.valueOf('S'), Items.STICK, Character.valueOf('C'), new ItemStack(Items.DYE, 1, 13)});
            GameRegistry.addRecipe(new ItemStack(ModDyeTools.magenta_hoe, 1), new Object[]{" CC", " S ", " S ", Character.valueOf('S'), Items.STICK, Character.valueOf('C'), new ItemStack(Items.DYE, 1, 13)});
            GameRegistry.addRecipe(new ItemStack(ModDyeTools.magenta_sword, 1), new Object[]{" C ", " C ", " S ", Character.valueOf('S'), Items.STICK, Character.valueOf('C'), new ItemStack(Items.DYE, 1, 13)});
            GameRegistry.addRecipe(new ItemStack(ModDyeTools.lightblue_pickaxe, 1), new Object[]{"CCC", " S ", " S ", Character.valueOf('S'), Items.STICK, Character.valueOf('C'), new ItemStack(Items.DYE, 1, 12)});
            GameRegistry.addRecipe(new ItemStack(ModDyeTools.lightblue_axe, 1), new Object[]{" CC", " SC", " S ", Character.valueOf('S'), Items.STICK, Character.valueOf('C'), new ItemStack(Items.DYE, 1, 12)});
            GameRegistry.addRecipe(new ItemStack(ModDyeTools.lightblue_shovel, 1), new Object[]{" C ", " S ", " S ", Character.valueOf('S'), Items.STICK, Character.valueOf('C'), new ItemStack(Items.DYE, 1, 12)});
            GameRegistry.addRecipe(new ItemStack(ModDyeTools.lightblue_hoe, 1), new Object[]{" CC", " S ", " S ", Character.valueOf('S'), Items.STICK, Character.valueOf('C'), new ItemStack(Items.DYE, 1, 12)});
            GameRegistry.addRecipe(new ItemStack(ModDyeTools.lightblue_sword, 1), new Object[]{" C ", " C ", " S ", Character.valueOf('S'), Items.STICK, Character.valueOf('C'), new ItemStack(Items.DYE, 1, 12)});
            GameRegistry.addRecipe(new ItemStack(ModDyeTools.yellow_pickaxe, 1), new Object[]{"CCC", " S ", " S ", Character.valueOf('S'), Items.STICK, Character.valueOf('C'), new ItemStack(Items.DYE, 1, 11)});
            GameRegistry.addRecipe(new ItemStack(ModDyeTools.yellow_axe, 1), new Object[]{" CC", " SC", " S ", Character.valueOf('S'), Items.STICK, Character.valueOf('C'), new ItemStack(Items.DYE, 1, 11)});
            GameRegistry.addRecipe(new ItemStack(ModDyeTools.yellow_shovel, 1), new Object[]{" C ", " S ", " S ", Character.valueOf('S'), Items.STICK, Character.valueOf('C'), new ItemStack(Items.DYE, 1, 11)});
            GameRegistry.addRecipe(new ItemStack(ModDyeTools.yellow_hoe, 1), new Object[]{" CC", " S ", " S ", Character.valueOf('S'), Items.STICK, Character.valueOf('C'), new ItemStack(Items.DYE, 1, 11)});
            GameRegistry.addRecipe(new ItemStack(ModDyeTools.yellow_sword, 1), new Object[]{" C ", " C ", " S ", Character.valueOf('S'), Items.STICK, Character.valueOf('C'), new ItemStack(Items.DYE, 1, 11)});
            GameRegistry.addRecipe(new ItemStack(ModDyeTools.lime_pickaxe, 1), new Object[]{"CCC", " S ", " S ", Character.valueOf('S'), Items.STICK, Character.valueOf('C'), new ItemStack(Items.DYE, 1, 10)});
            GameRegistry.addRecipe(new ItemStack(ModDyeTools.lime_axe, 1), new Object[]{" CC", " SC", " S ", Character.valueOf('S'), Items.STICK, Character.valueOf('C'), new ItemStack(Items.DYE, 1, 10)});
            GameRegistry.addRecipe(new ItemStack(ModDyeTools.lime_shovel, 1), new Object[]{" C ", " S ", " S ", Character.valueOf('S'), Items.STICK, Character.valueOf('C'), new ItemStack(Items.DYE, 1, 10)});
            GameRegistry.addRecipe(new ItemStack(ModDyeTools.lime_hoe, 1), new Object[]{" CC", " S ", " S ", Character.valueOf('S'), Items.STICK, Character.valueOf('C'), new ItemStack(Items.DYE, 1, 10)});
            GameRegistry.addRecipe(new ItemStack(ModDyeTools.lime_sword, 1), new Object[]{" C ", " C ", " S ", Character.valueOf('S'), Items.STICK, Character.valueOf('C'), new ItemStack(Items.DYE, 1, 10)});
            GameRegistry.addRecipe(new ItemStack(ModDyeTools.pink_pickaxe, 1), new Object[]{"CCC", " S ", " S ", Character.valueOf('S'), Items.STICK, Character.valueOf('C'), new ItemStack(Items.DYE, 1, 9)});
            GameRegistry.addRecipe(new ItemStack(ModDyeTools.pink_axe, 1), new Object[]{" CC", " SC", " S ", Character.valueOf('S'), Items.STICK, Character.valueOf('C'), new ItemStack(Items.DYE, 1, 9)});
            GameRegistry.addRecipe(new ItemStack(ModDyeTools.pink_shovel, 1), new Object[]{" C ", " S ", " S ", Character.valueOf('S'), Items.STICK, Character.valueOf('C'), new ItemStack(Items.DYE, 1, 9)});
            GameRegistry.addRecipe(new ItemStack(ModDyeTools.pink_hoe, 1), new Object[]{" CC", " S ", " S ", Character.valueOf('S'), Items.STICK, Character.valueOf('C'), new ItemStack(Items.DYE, 1, 9)});
            GameRegistry.addRecipe(new ItemStack(ModDyeTools.pink_sword, 1), new Object[]{" C ", " C ", " S ", Character.valueOf('S'), Items.STICK, Character.valueOf('C'), new ItemStack(Items.DYE, 1, 9)});
            GameRegistry.addRecipe(new ItemStack(ModDyeTools.gray_pickaxe, 1), new Object[]{"CCC", " S ", " S ", Character.valueOf('S'), Items.STICK, Character.valueOf('C'), new ItemStack(Items.DYE, 1, 8)});
            GameRegistry.addRecipe(new ItemStack(ModDyeTools.gray_axe, 1), new Object[]{" CC", " SC", " S ", Character.valueOf('S'), Items.STICK, Character.valueOf('C'), new ItemStack(Items.DYE, 1, 8)});
            GameRegistry.addRecipe(new ItemStack(ModDyeTools.gray_shovel, 1), new Object[]{" C ", " S ", " S ", Character.valueOf('S'), Items.STICK, Character.valueOf('C'), new ItemStack(Items.DYE, 1, 8)});
            GameRegistry.addRecipe(new ItemStack(ModDyeTools.gray_hoe, 1), new Object[]{" CC", " S ", " S ", Character.valueOf('S'), Items.STICK, Character.valueOf('C'), new ItemStack(Items.DYE, 1, 8)});
            GameRegistry.addRecipe(new ItemStack(ModDyeTools.gray_sword, 1), new Object[]{" C ", " C ", " S ", Character.valueOf('S'), Items.STICK, Character.valueOf('C'), new ItemStack(Items.DYE, 1, 8)});
            GameRegistry.addRecipe(new ItemStack(ModDyeTools.lightgray_pickaxe, 1), new Object[]{"CCC", " S ", " S ", Character.valueOf('S'), Items.STICK, Character.valueOf('C'), new ItemStack(Items.DYE, 1, 7)});
            GameRegistry.addRecipe(new ItemStack(ModDyeTools.lightgray_axe, 1), new Object[]{" CC", " SC", " S ", Character.valueOf('S'), Items.STICK, Character.valueOf('C'), new ItemStack(Items.DYE, 1, 7)});
            GameRegistry.addRecipe(new ItemStack(ModDyeTools.lightgray_shovel, 1), new Object[]{" C ", " S ", " S ", Character.valueOf('S'), Items.STICK, Character.valueOf('C'), new ItemStack(Items.DYE, 1, 7)});
            GameRegistry.addRecipe(new ItemStack(ModDyeTools.lightgray_hoe, 1), new Object[]{" CC", " S ", " S ", Character.valueOf('S'), Items.STICK, Character.valueOf('C'), new ItemStack(Items.DYE, 1, 7)});
            GameRegistry.addRecipe(new ItemStack(ModDyeTools.lightgray_sword, 1), new Object[]{" C ", " C ", " S ", Character.valueOf('S'), Items.STICK, Character.valueOf('C'), new ItemStack(Items.DYE, 1, 7)});
            GameRegistry.addRecipe(new ItemStack(ModDyeTools.cyan_pickaxe, 1), new Object[]{"CCC", " S ", " S ", Character.valueOf('S'), Items.STICK, Character.valueOf('C'), new ItemStack(Items.DYE, 1, 6)});
            GameRegistry.addRecipe(new ItemStack(ModDyeTools.cyan_axe, 1), new Object[]{" CC", " SC", " S ", Character.valueOf('S'), Items.STICK, Character.valueOf('C'), new ItemStack(Items.DYE, 1, 6)});
            GameRegistry.addRecipe(new ItemStack(ModDyeTools.cyan_shovel, 1), new Object[]{" C ", " S ", " S ", Character.valueOf('S'), Items.STICK, Character.valueOf('C'), new ItemStack(Items.DYE, 1, 6)});
            GameRegistry.addRecipe(new ItemStack(ModDyeTools.cyan_hoe, 1), new Object[]{" CC", " S ", " S ", Character.valueOf('S'), Items.STICK, Character.valueOf('C'), new ItemStack(Items.DYE, 1, 6)});
            GameRegistry.addRecipe(new ItemStack(ModDyeTools.cyan_sword, 1), new Object[]{" C ", " C ", " S ", Character.valueOf('S'), Items.STICK, Character.valueOf('C'), new ItemStack(Items.DYE, 1, 6)});
            GameRegistry.addRecipe(new ItemStack(ModDyeTools.purple_pickaxe, 1), new Object[]{"CCC", " S ", " S ", Character.valueOf('S'), Items.STICK, Character.valueOf('C'), new ItemStack(Items.DYE, 1, 5)});
            GameRegistry.addRecipe(new ItemStack(ModDyeTools.purple_axe, 1), new Object[]{" CC", " SC", " S ", Character.valueOf('S'), Items.STICK, Character.valueOf('C'), new ItemStack(Items.DYE, 1, 5)});
            GameRegistry.addRecipe(new ItemStack(ModDyeTools.purple_shovel, 1), new Object[]{" C ", " S ", " S ", Character.valueOf('S'), Items.STICK, Character.valueOf('C'), new ItemStack(Items.DYE, 1, 5)});
            GameRegistry.addRecipe(new ItemStack(ModDyeTools.purple_hoe, 1), new Object[]{" CC", " S ", " S ", Character.valueOf('S'), Items.STICK, Character.valueOf('C'), new ItemStack(Items.DYE, 1, 5)});
            GameRegistry.addRecipe(new ItemStack(ModDyeTools.purple_sword, 1), new Object[]{" C ", " C ", " S ", Character.valueOf('S'), Items.STICK, Character.valueOf('C'), new ItemStack(Items.DYE, 1, 5)});
            GameRegistry.addRecipe(new ItemStack(ModDyeTools.blue_pickaxe, 1), new Object[]{"CCC", " S ", " S ", Character.valueOf('S'), Items.STICK, Character.valueOf('C'), new ItemStack(Items.DYE, 1, 4)});
            GameRegistry.addRecipe(new ItemStack(ModDyeTools.blue_axe, 1), new Object[]{" CC", " SC", " S ", Character.valueOf('S'), Items.STICK, Character.valueOf('C'), new ItemStack(Items.DYE, 1, 4)});
            GameRegistry.addRecipe(new ItemStack(ModDyeTools.blue_shovel, 1), new Object[]{" C ", " S ", " S ", Character.valueOf('S'), Items.STICK, Character.valueOf('C'), new ItemStack(Items.DYE, 1, 4)});
            GameRegistry.addRecipe(new ItemStack(ModDyeTools.blue_hoe, 1), new Object[]{" CC", " S ", " S ", Character.valueOf('S'), Items.STICK, Character.valueOf('C'), new ItemStack(Items.DYE, 1, 4)});
            GameRegistry.addRecipe(new ItemStack(ModDyeTools.blue_sword, 1), new Object[]{" C ", " C ", " S ", Character.valueOf('S'), Items.STICK, Character.valueOf('C'), new ItemStack(Items.DYE, 1, 4)});
            GameRegistry.addRecipe(new ItemStack(ModDyeTools.brown_pickaxe, 1), new Object[]{"CCC", " S ", " S ", Character.valueOf('S'), Items.STICK, Character.valueOf('C'), new ItemStack(Items.DYE, 1, 3)});
            GameRegistry.addRecipe(new ItemStack(ModDyeTools.brown_axe, 1), new Object[]{" CC", " SC", " S ", Character.valueOf('S'), Items.STICK, Character.valueOf('C'), new ItemStack(Items.DYE, 1, 3)});
            GameRegistry.addRecipe(new ItemStack(ModDyeTools.brown_shovel, 1), new Object[]{" C ", " S ", " S ", Character.valueOf('S'), Items.STICK, Character.valueOf('C'), new ItemStack(Items.DYE, 1, 3)});
            GameRegistry.addRecipe(new ItemStack(ModDyeTools.brown_hoe, 1), new Object[]{" CC", " S ", " S ", Character.valueOf('S'), Items.STICK, Character.valueOf('C'), new ItemStack(Items.DYE, 1, 3)});
            GameRegistry.addRecipe(new ItemStack(ModDyeTools.brown_sword, 1), new Object[]{" C ", " C ", " S ", Character.valueOf('S'), Items.STICK, Character.valueOf('C'), new ItemStack(Items.DYE, 1, 3)});
            GameRegistry.addRecipe(new ItemStack(ModDyeTools.green_pickaxe, 1), new Object[]{"CCC", " S ", " S ", Character.valueOf('S'), Items.STICK, Character.valueOf('C'), new ItemStack(Items.DYE, 1, 2)});
            GameRegistry.addRecipe(new ItemStack(ModDyeTools.green_axe, 1), new Object[]{" CC", " SC", " S ", Character.valueOf('S'), Items.STICK, Character.valueOf('C'), new ItemStack(Items.DYE, 1, 2)});
            GameRegistry.addRecipe(new ItemStack(ModDyeTools.green_shovel, 1), new Object[]{" C ", " S ", " S ", Character.valueOf('S'), Items.STICK, Character.valueOf('C'), new ItemStack(Items.DYE, 1, 2)});
            GameRegistry.addRecipe(new ItemStack(ModDyeTools.green_hoe, 1), new Object[]{" CC", " S ", " S ", Character.valueOf('S'), Items.STICK, Character.valueOf('C'), new ItemStack(Items.DYE, 1, 2)});
            GameRegistry.addRecipe(new ItemStack(ModDyeTools.green_sword, 1), new Object[]{" C ", " C ", " S ", Character.valueOf('S'), Items.STICK, Character.valueOf('C'), new ItemStack(Items.DYE, 1, 2)});
            GameRegistry.addRecipe(new ItemStack(ModDyeTools.red_pickaxe, 1), new Object[]{"CCC", " S ", " S ", Character.valueOf('S'), Items.STICK, Character.valueOf('C'), new ItemStack(Items.DYE, 1, 1)});
            GameRegistry.addRecipe(new ItemStack(ModDyeTools.red_axe, 1), new Object[]{" CC", " SC", " S ", Character.valueOf('S'), Items.STICK, Character.valueOf('C'), new ItemStack(Items.DYE, 1, 1)});
            GameRegistry.addRecipe(new ItemStack(ModDyeTools.red_shovel, 1), new Object[]{" C ", " S ", " S ", Character.valueOf('S'), Items.STICK, Character.valueOf('C'), new ItemStack(Items.DYE, 1, 1)});
            GameRegistry.addRecipe(new ItemStack(ModDyeTools.red_hoe, 1), new Object[]{" CC", " S ", " S ", Character.valueOf('S'), Items.STICK, Character.valueOf('C'), new ItemStack(Items.DYE, 1, 1)});
            GameRegistry.addRecipe(new ItemStack(ModDyeTools.red_sword, 1), new Object[]{" C ", " C ", " S ", Character.valueOf('S'), Items.STICK, Character.valueOf('C'), new ItemStack(Items.DYE, 1, 1)});
            GameRegistry.addRecipe(new ItemStack(ModDyeTools.black_pickaxe, 1), new Object[]{"CCC", " S ", " S ", Character.valueOf('S'), Items.STICK, Character.valueOf('C'), new ItemStack(Items.DYE, 1, 0)});
            GameRegistry.addRecipe(new ItemStack(ModDyeTools.black_axe, 1), new Object[]{" CC", " SC", " S ", Character.valueOf('S'), Items.STICK, Character.valueOf('C'), new ItemStack(Items.DYE, 1, 0)});
            GameRegistry.addRecipe(new ItemStack(ModDyeTools.black_shovel, 1), new Object[]{" C ", " S ", " S ", Character.valueOf('S'), Items.STICK, Character.valueOf('C'), new ItemStack(Items.DYE, 1, 0)});
            GameRegistry.addRecipe(new ItemStack(ModDyeTools.black_hoe, 1), new Object[]{" CC", " S ", " S ", Character.valueOf('S'), Items.STICK, Character.valueOf('C'), new ItemStack(Items.DYE, 1, 0)});
            GameRegistry.addRecipe(new ItemStack(ModDyeTools.black_sword, 1), new Object[]{" C ", " C ", " S ", Character.valueOf('S'), Items.STICK, Character.valueOf('C'), new ItemStack(Items.DYE, 1, 0)});
            GameRegistry.addRecipe(new ItemStack(ModTools.nstar_paxel, 1), new Object[]{"ASP", " # ", " # ", 'A', ModTools.nstar_axe, 'S', ModTools.nstar_shovel, 'P', ModTools.nstar_pickaxe, '#', Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.obsidian_paxel, 1), new Object[]{"ASP", " # ", " # ", 'A', ModTools.obsidian_axe, 'S', ModTools.obsidian_shovel, 'P', ModTools.obsidian_pickaxe, '#', Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.emerald_paxel, 1), new Object[]{"ASP", " # ", " # ", 'A', ModTools.emerald_axe, 'S', ModTools.emerald_shovel, 'P', ModTools.emerald_pickaxe, '#', Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.ender_paxel, 1), new Object[]{"ASP", " # ", " # ", 'A', ModTools.ender_axe, 'S', ModTools.ender_shovel, 'P', ModTools.ender_pickaxe, '#', Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.glowstone_paxel, 1), new Object[]{"ASP", " # ", " # ", 'A', ModTools.glowstone_axe, 'S', ModTools.glowstone_shovel, 'P', ModTools.glowstone_pickaxe, '#', Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.redstone_paxel, 1), new Object[]{"ASP", " # ", " # ", 'A', ModTools.redstone_axe, 'S', ModTools.redstone_shovel, 'P', ModTools.redstone_pickaxe, '#', Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.coal_paxel, 1), new Object[]{"ASP", " # ", " # ", 'A', ModTools.coal_axe, 'S', ModTools.coal_shovel, 'P', ModTools.coal_pickaxe, '#', Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.gunpowder_paxel, 1), new Object[]{"ASP", " # ", " # ", 'A', ModTools.gunpowder_axe, 'S', ModTools.gunpowder_shovel, 'P', ModTools.gunpowder_pickaxe, '#', Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.flint_paxel, 1), new Object[]{"ASP", " # ", " # ", 'A', ModTools.flint_axe, 'S', ModTools.flint_shovel, 'P', ModTools.flint_pickaxe, '#', Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.magma_cream_paxel, 1), new Object[]{"ASP", " # ", " # ", 'A', ModTools.magma_cream_axe, 'S', ModTools.magma_cream_shovel, 'P', ModTools.magma_cream_pickaxe, '#', Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.sandstone_paxel, 1), new Object[]{"ASP", " # ", " # ", 'A', ModTools.sandstone_axe, 'S', ModTools.sandstone_shovel, 'P', ModTools.sandstone_pickaxe, '#', Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.soul_sand_paxel, 1), new Object[]{"ASP", " # ", " # ", 'A', ModTools.soul_sand_axe, 'S', ModTools.soul_sand_shovel, 'P', ModTools.soul_sand_pickaxe, '#', Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.snow_paxel, 1), new Object[]{"ASP", " # ", " # ", 'A', ModTools.snow_axe, 'S', ModTools.snow_shovel, 'P', ModTools.snow_pickaxe, '#', Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.slime_paxel, 1), new Object[]{"ASP", " # ", " # ", 'A', ModTools.slime_axe, 'S', ModTools.slime_shovel, 'P', ModTools.slime_pickaxe, '#', Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.blaze_paxel, 1), new Object[]{"ASP", " # ", " # ", 'A', ModTools.blaze_axe, 'S', ModTools.blaze_shovel, 'P', ModTools.blaze_pickaxe, '#', Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.brick_paxel, 1), new Object[]{"ASP", " # ", " # ", 'A', ModTools.brick_axe, 'S', ModTools.brick_shovel, 'P', ModTools.brick_pickaxe, '#', Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.nbrick_paxel, 1), new Object[]{"ASP", " # ", " # ", 'A', ModTools.nbrick_axe, 'S', ModTools.nbrick_shovel, 'P', ModTools.nbrick_pickaxe, '#', Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.leather_paxel, 1), new Object[]{"ASP", " # ", " # ", 'A', ModTools.leather_axe, 'S', ModTools.leather_shovel, 'P', ModTools.leather_pickaxe, '#', Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.clay_paxel, 1), new Object[]{"ASP", " # ", " # ", 'A', ModTools.clay_axe, 'S', ModTools.clay_shovel, 'P', ModTools.clay_pickaxe, '#', Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.quartz_paxel, 1), new Object[]{"ASP", " # ", " # ", 'A', ModTools.quartz_axe, 'S', ModTools.quartz_shovel, 'P', ModTools.quartz_pickaxe, '#', Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModToolDyePaxels.black_paxel, 1), new Object[]{"ASP", " # ", " # ", 'A', ModDyeTools.black_axe, 'S', ModDyeTools.black_shovel, 'P', ModDyeTools.black_axe, '#', Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModToolDyePaxels.red_paxel, 1), new Object[]{"ASP", " # ", " # ", 'A', ModDyeTools.red_axe, 'S', ModDyeTools.red_shovel, 'P', ModDyeTools.red_pickaxe, '#', Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModToolDyePaxels.green_paxel, 1), new Object[]{"ASP", " # ", " # ", 'A', ModDyeTools.green_axe, 'S', ModDyeTools.green_shovel, 'P', ModDyeTools.green_pickaxe, '#', Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModToolDyePaxels.brown_paxel, 1), new Object[]{"ASP", " # ", " # ", 'A', ModDyeTools.brown_axe, 'S', ModDyeTools.brown_shovel, 'P', ModDyeTools.brown_pickaxe, '#', Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModToolDyePaxels.blue_paxel, 1), new Object[]{"ASP", " # ", " # ", 'A', ModDyeTools.blue_axe, 'S', ModDyeTools.blue_shovel, 'P', ModDyeTools.blue_pickaxe, '#', Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModToolDyePaxels.purple_paxel, 1), new Object[]{"ASP", " # ", " # ", 'A', ModDyeTools.purple_axe, 'S', ModDyeTools.purple_shovel, 'P', ModDyeTools.purple_pickaxe, '#', Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModToolDyePaxels.cyan_paxel, 1), new Object[]{"ASP", " # ", " # ", 'A', ModDyeTools.cyan_axe, 'S', ModDyeTools.cyan_shovel, 'P', ModDyeTools.cyan_pickaxe, '#', Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModToolDyePaxels.gray_paxel, 1), new Object[]{"ASP", " # ", " # ", 'A', ModDyeTools.gray_axe, 'S', ModDyeTools.gray_shovel, 'P', ModDyeTools.gray_pickaxe, '#', Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModToolDyePaxels.lightgray_paxel, 1), new Object[]{"ASP", " # ", " # ", 'A', ModDyeTools.lightgray_axe, 'S', ModDyeTools.lightgray_shovel, 'P', ModDyeTools.lightgray_pickaxe, '#', Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModToolDyePaxels.pink_paxel, 1), new Object[]{"ASP", " # ", " # ", 'A', ModDyeTools.pink_axe, 'S', ModDyeTools.pink_shovel, 'P', ModDyeTools.pink_pickaxe, '#', Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModToolDyePaxels.lime_paxel, 1), new Object[]{"ASP", " # ", " # ", 'A', ModDyeTools.lime_axe, 'S', ModDyeTools.lime_shovel, 'P', ModDyeTools.lime_pickaxe, '#', Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModToolDyePaxels.yellow_paxel, 1), new Object[]{"ASP", " # ", " # ", 'A', ModDyeTools.yellow_axe, 'S', ModDyeTools.yellow_shovel, 'P', ModDyeTools.yellow_pickaxe, '#', Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModToolDyePaxels.lightblue_paxel, 1), new Object[]{"ASP", " # ", " # ", 'A', ModDyeTools.lightblue_axe, 'S', ModDyeTools.lightblue_shovel, 'P', ModDyeTools.lightblue_pickaxe, '#', Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModToolDyePaxels.magenta_paxel, 1), new Object[]{"ASP", " # ", " # ", 'A', ModDyeTools.magenta_axe, 'S', ModDyeTools.magenta_shovel, 'P', ModDyeTools.magenta_pickaxe, '#', Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModToolDyePaxels.orange_paxel, 1), new Object[]{"ASP", " # ", " # ", 'A', ModDyeTools.orange_axe, 'S', ModDyeTools.orange_shovel, 'P', ModDyeTools.orange_pickaxe, '#', Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModToolDyePaxels.white_paxel, 1), new Object[]{"ASP", " # ", " # ", 'A', ModDyeTools.white_axe, 'S', ModDyeTools.white_shovel, 'P', ModDyeTools.white_pickaxe, '#', Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.wooden_paxel, 1), new Object[]{"ASP", " # ", " # ", 'A', Items.WOODEN_AXE, 'S', Items.WOODEN_SHOVEL, 'P', Items.WOODEN_PICKAXE, '#', Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.stone_paxel, 1), new Object[]{"ASP", " # ", " # ", 'A', Items.STONE_AXE, 'S', Items.STONE_SHOVEL, 'P', Items.STONE_PICKAXE, '#', Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.iron_paxel, 1), new Object[]{"ASP", " # ", " # ", 'A', Items.IRON_AXE, 'S', Items.IRON_SHOVEL, 'P', Items.IRON_PICKAXE, '#', Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.gold_paxel, 1), new Object[]{"ASP", " # ", " # ", 'A', Items.GOLDEN_AXE, 'S', Items.GOLDEN_SHOVEL, 'P', Items.GOLDEN_PICKAXE, '#', Items.STICK});
            GameRegistry.addRecipe(new ItemStack(ModTools.diamond_paxel, 1), new Object[]{"ASP", " # ", " # ", 'A', Items.DIAMOND_AXE, 'S', Items.DIAMOND_SHOVEL, 'P', Items.DIAMOND_PICKAXE, '#', Items.STICK});
        }
        //PattysMoreArmor
        if (ConfigPreInit.disableArmor) {
            GameRegistry.addRecipe(new ItemStack(ModArmor.obsidian_helmet, 1), new Object[]{"OOO", "O O", 'O', ModPMS.obsidian_ingot});
            GameRegistry.addRecipe(new ItemStack(ModArmor.obsidian_chestplate, 1), new Object[]{"O O", "OOO", "OOO", 'O', ModPMS.obsidian_ingot});
            GameRegistry.addRecipe(new ItemStack(ModArmor.obsidian_leggings, 1), new Object[]{"OOO", "O O", "O O", 'O', ModPMS.obsidian_ingot});
            GameRegistry.addRecipe(new ItemStack(ModArmor.obsidian_boots, 1), new Object[]{"O O", "O O", 'O', ModPMS.obsidian_ingot});
            GameRegistry.addRecipe(new ItemStack(ModArmor.emerald_helmet, 1), new Object[]{"OOO", "O O", Character.valueOf('O'), Items.EMERALD});
            GameRegistry.addRecipe(new ItemStack(ModArmor.emerald_chestplate, 1), new Object[]{"O O", "OOO", "OOO", Character.valueOf('O'), Items.EMERALD});
            GameRegistry.addRecipe(new ItemStack(ModArmor.emerald_leggings, 1), new Object[]{"OOO", "O O", "O O", Character.valueOf('O'), Items.EMERALD});
            GameRegistry.addRecipe(new ItemStack(ModArmor.emerald_boots, 1), new Object[]{"O O", "O O", Character.valueOf('O'), Items.EMERALD});
            GameRegistry.addRecipe(new ItemStack(ModArmor.ender_helmet, 1), new Object[]{"OOO", "O O", Character.valueOf('O'), Items.ENDER_PEARL});
            GameRegistry.addRecipe(new ItemStack(ModArmor.ender_chestplate, 1), new Object[]{"O O", "OOO", "OOO", Character.valueOf('O'), Items.ENDER_PEARL});
            GameRegistry.addRecipe(new ItemStack(ModArmor.ender_leggings, 1), new Object[]{"OOO", "O O", "O O", Character.valueOf('O'), Items.ENDER_PEARL});
            GameRegistry.addRecipe(new ItemStack(ModArmor.ender_boots, 1), new Object[]{"O O", "O O", Character.valueOf('O'), Items.ENDER_PEARL});
            GameRegistry.addRecipe(new ItemStack(ModArmor.slime_helmet, 1), new Object[]{"OOO", "O O", Character.valueOf('O'), Items.SLIME_BALL});
            GameRegistry.addRecipe(new ItemStack(ModArmor.slime_chestplate, 1), new Object[]{"O O", "OOO", "OOO", Character.valueOf('O'), Items.SLIME_BALL});
            GameRegistry.addRecipe(new ItemStack(ModArmor.slime_leggings, 1), new Object[]{"OOO", "O O", "O O", Character.valueOf('O'), Items.SLIME_BALL});
            GameRegistry.addRecipe(new ItemStack(ModArmor.slime_boots, 1), new Object[]{"O O", "O O", Character.valueOf('O'), Items.SLIME_BALL});
            GameRegistry.addRecipe(new ItemStack(ModArmor.coal_helmet, 1), new Object[]{"OOO", "O O", Character.valueOf('O'), Items.COAL});
            GameRegistry.addRecipe(new ItemStack(ModArmor.coal_chestplate, 1), new Object[]{"O O", "OOO", "OOO", Character.valueOf('O'), Items.COAL});
            GameRegistry.addRecipe(new ItemStack(ModArmor.coal_leggings, 1), new Object[]{"OOO", "O O", "O O", Character.valueOf('O'), Items.COAL});
            GameRegistry.addRecipe(new ItemStack(ModArmor.coal_boots, 1), new Object[]{"O O", "O O", Character.valueOf('O'), Items.COAL});
            GameRegistry.addRecipe(new ItemStack(ModArmor.quartz_helmet, 1), new Object[]{"OOO", "O O", Character.valueOf('O'), Items.QUARTZ});
            GameRegistry.addRecipe(new ItemStack(ModArmor.quartz_chestplate, 1), new Object[]{"O O", "OOO", "OOO", Character.valueOf('O'), Items.QUARTZ});
            GameRegistry.addRecipe(new ItemStack(ModArmor.quartz_leggings, 1), new Object[]{"OOO", "O O", "O O", Character.valueOf('O'), Items.QUARTZ});
            GameRegistry.addRecipe(new ItemStack(ModArmor.quartz_boots, 1), new Object[]{"O O", "O O", Character.valueOf('O'), Items.QUARTZ});
            GameRegistry.addRecipe(new ItemStack(ModArmor.flint_helmet, 1), new Object[]{"OOO", "O O", Character.valueOf('O'), Items.FLINT});
            GameRegistry.addRecipe(new ItemStack(ModArmor.flint_chestplate, 1), new Object[]{"O O", "OOO", "OOO", Character.valueOf('O'), Items.FLINT});
            GameRegistry.addRecipe(new ItemStack(ModArmor.flint_leggings, 1), new Object[]{"OOO", "O O", "O O", Character.valueOf('O'), Items.FLINT});
            GameRegistry.addRecipe(new ItemStack(ModArmor.flint_boots, 1), new Object[]{"O O", "O O", Character.valueOf('O'), Items.FLINT});
            GameRegistry.addRecipe(new ItemStack(ModArmor.gunpowder_helmet, 1), new Object[]{"OOO", "O O", Character.valueOf('O'), Items.GUNPOWDER});
            GameRegistry.addRecipe(new ItemStack(ModArmor.gunpowder_chestplate, 1), new Object[]{"O O", "OOO", "OOO", Character.valueOf('O'), Items.GUNPOWDER});
            GameRegistry.addRecipe(new ItemStack(ModArmor.gunpowder_leggings, 1), new Object[]{"OOO", "O O", "O O", Character.valueOf('O'), Items.GUNPOWDER});
            GameRegistry.addRecipe(new ItemStack(ModArmor.gunpowder_boots, 1), new Object[]{"O O", "O O", Character.valueOf('O'), Items.GUNPOWDER});
            GameRegistry.addRecipe(new ItemStack(ModArmor.glowstone_helmet, 1), new Object[]{"OOO", "O O", Character.valueOf('O'), Items.GLOWSTONE_DUST});
            GameRegistry.addRecipe(new ItemStack(ModArmor.glowstone_chestplate, 1), new Object[]{"O O", "OOO", "OOO", Character.valueOf('O'), Items.GLOWSTONE_DUST});
            GameRegistry.addRecipe(new ItemStack(ModArmor.glowstone_leggings, 1), new Object[]{"OOO", "O O", "O O", Character.valueOf('O'), Items.GLOWSTONE_DUST});
            GameRegistry.addRecipe(new ItemStack(ModArmor.glowstone_boots, 1), new Object[]{"O O", "O O", Character.valueOf('O'), Items.GLOWSTONE_DUST});
            GameRegistry.addRecipe(new ItemStack(ModArmor.brick_helmet, 1), new Object[]{"OOO", "O O", Character.valueOf('O'), Items.BRICK});
            GameRegistry.addRecipe(new ItemStack(ModArmor.brick_chestplate, 1), new Object[]{"O O", "OOO", "OOO", Character.valueOf('O'), Items.BRICK});
            GameRegistry.addRecipe(new ItemStack(ModArmor.brick_leggings, 1), new Object[]{"OOO", "O O", "O O", Character.valueOf('O'), Items.BRICK});
            GameRegistry.addRecipe(new ItemStack(ModArmor.brick_boots, 1), new Object[]{"O O", "O O", Character.valueOf('O'), Items.BRICK});
            GameRegistry.addRecipe(new ItemStack(ModArmor.nether_brick_helmet, 1), new Object[]{"OOO", "O O", Character.valueOf('O'), Items.NETHERBRICK});
            GameRegistry.addRecipe(new ItemStack(ModArmor.nether_brick_chestplate, 1), new Object[]{"O O", "OOO", "OOO", Character.valueOf('O'), Items.NETHERBRICK});
            GameRegistry.addRecipe(new ItemStack(ModArmor.nether_brick_leggings, 1), new Object[]{"OOO", "O O", "O O", Character.valueOf('O'), Items.NETHERBRICK});
            GameRegistry.addRecipe(new ItemStack(ModArmor.nether_brick_boots, 1), new Object[]{"O O", "O O", Character.valueOf('O'), Items.NETHERBRICK});
            GameRegistry.addRecipe(new ItemStack(ModArmor.redstone_helmet, 1), new Object[]{"OOO", "O O", Character.valueOf('O'), Items.REDSTONE});
            GameRegistry.addRecipe(new ItemStack(ModArmor.redstone_chestplate, 1), new Object[]{"O O", "OOO", "OOO", Character.valueOf('O'), Items.REDSTONE});
            GameRegistry.addRecipe(new ItemStack(ModArmor.redstone_leggings, 1), new Object[]{"OOO", "O O", "O O", Character.valueOf('O'), Items.REDSTONE});
            GameRegistry.addRecipe(new ItemStack(ModArmor.redstone_boots, 1), new Object[]{"O O", "O O", Character.valueOf('O'), Items.REDSTONE});
            GameRegistry.addRecipe(new ItemStack(ModArmor.blaze_helmet, 1), new Object[]{"OOO", "O O", Character.valueOf('O'), Items.BLAZE_POWDER});
            GameRegistry.addRecipe(new ItemStack(ModArmor.blaze_chestplate, 1), new Object[]{"O O", "OOO", "OOO", Character.valueOf('O'), Items.BLAZE_POWDER});
            GameRegistry.addRecipe(new ItemStack(ModArmor.blaze_leggings, 1), new Object[]{"OOO", "O O", "O O", Character.valueOf('O'), Items.BLAZE_POWDER});
            GameRegistry.addRecipe(new ItemStack(ModArmor.blaze_boots, 1), new Object[]{"O O", "O O", Character.valueOf('O'), Items.BLAZE_POWDER});
            GameRegistry.addRecipe(new ItemStack(ModArmor.nether_star_helmet, 1), new Object[]{"OOO", "O O", Character.valueOf('O'), Items.NETHER_STAR});
            GameRegistry.addRecipe(new ItemStack(ModArmor.nether_star_chestplate, 1), new Object[]{"O O", "OOO", "OOO", Character.valueOf('O'), Items.NETHER_STAR});
            GameRegistry.addRecipe(new ItemStack(ModArmor.nether_star_leggings, 1), new Object[]{"OOO", "O O", "O O", Character.valueOf('O'), Items.NETHER_STAR});
            GameRegistry.addRecipe(new ItemStack(ModArmor.nether_star_boots, 1), new Object[]{"O O", "O O", Character.valueOf('O'), Items.NETHER_STAR});
            GameRegistry.addRecipe(new ItemStack(ModArmor.snow_helmet, 1), new Object[]{"OOO", "O O", Character.valueOf('O'), Items.SNOWBALL});
            GameRegistry.addRecipe(new ItemStack(ModArmor.snow_chestplate, 1), new Object[]{"O O", "OOO", "OOO", Character.valueOf('O'), Items.SNOWBALL});
            GameRegistry.addRecipe(new ItemStack(ModArmor.snow_leggings, 1), new Object[]{"OOO", "O O", "O O", Character.valueOf('O'), Items.SNOWBALL});
            GameRegistry.addRecipe(new ItemStack(ModArmor.snow_boots, 1), new Object[]{"O O", "O O", Character.valueOf('O'), Items.SNOWBALL});
            GameRegistry.addRecipe(new ItemStack(ModArmor.magma_cream_helmet, 1), new Object[]{"OOO", "O O", Character.valueOf('O'), Items.MAGMA_CREAM});
            GameRegistry.addRecipe(new ItemStack(ModArmor.magma_cream_chestplate, 1), new Object[]{"O O", "OOO", "OOO", Character.valueOf('O'), Items.MAGMA_CREAM});
            GameRegistry.addRecipe(new ItemStack(ModArmor.magma_cream_leggings, 1), new Object[]{"OOO", "O O", "O O", Character.valueOf('O'), Items.MAGMA_CREAM});
            GameRegistry.addRecipe(new ItemStack(ModArmor.magma_cream_boots, 1), new Object[]{"O O", "O O", Character.valueOf('O'), Items.MAGMA_CREAM});
            GameRegistry.addRecipe(new ItemStack(ModArmor.sandstone_helmet, 1), new Object[]{"OOO", "O O", Character.valueOf('O'), Blocks.SANDSTONE});
            GameRegistry.addRecipe(new ItemStack(ModArmor.sandstone_chestplate, 1), new Object[]{"O O", "OOO", "OOO", Character.valueOf('O'), Blocks.SANDSTONE});
            GameRegistry.addRecipe(new ItemStack(ModArmor.sandstone_leggings, 1), new Object[]{"OOO", "O O", "O O", Character.valueOf('O'), Blocks.SANDSTONE});
            GameRegistry.addRecipe(new ItemStack(ModArmor.sandstone_boots, 1), new Object[]{"O O", "O O", Character.valueOf('O'), Blocks.SANDSTONE});
            GameRegistry.addRecipe(new ItemStack(ModArmor.soul_sand_helmet, 1), new Object[]{"OOO", "O O", Character.valueOf('O'), Blocks.SOUL_SAND});
            GameRegistry.addRecipe(new ItemStack(ModArmor.soul_sand_chestplate, 1), new Object[]{"O O", "OOO", "OOO", Character.valueOf('O'), Blocks.SOUL_SAND});
            GameRegistry.addRecipe(new ItemStack(ModArmor.soul_sand_leggings, 1), new Object[]{"OOO", "O O", "O O", Character.valueOf('O'), Blocks.SOUL_SAND});
            GameRegistry.addRecipe(new ItemStack(ModArmor.soul_sand_boots, 1), new Object[]{"O O", "O O", Character.valueOf('O'), Blocks.SOUL_SAND});
            GameRegistry.addRecipe(new ItemStack(ModArmor.clay_helmet, 1), new Object[]{"OOO", "O O", Character.valueOf('O'), Items.CLAY_BALL});
            GameRegistry.addRecipe(new ItemStack(ModArmor.clay_chestplate, 1), new Object[]{"O O", "OOO", "OOO", Character.valueOf('O'), Items.CLAY_BALL});
            GameRegistry.addRecipe(new ItemStack(ModArmor.clay_leggings, 1), new Object[]{"OOO", "O O", "O O", Character.valueOf('O'), Items.CLAY_BALL});
            GameRegistry.addRecipe(new ItemStack(ModArmor.clay_boots, 1), new Object[]{"O O", "O O", Character.valueOf('O'), Items.CLAY_BALL});
            GameRegistry.addRecipe(new ItemStack(ModDyeArmor.black_helmet, 1), new Object[]{"DDD", "D D", Character.valueOf('D'), new ItemStack(Items.DYE, 1, 0)});
            GameRegistry.addRecipe(new ItemStack(ModDyeArmor.black_chestplate, 1), new Object[]{"D D", "DDD", "DDD", Character.valueOf('D'), new ItemStack(Items.DYE, 1, 0)});
            GameRegistry.addRecipe(new ItemStack(ModDyeArmor.black_leggings, 1), new Object[]{"DDD", "D D", "D D", Character.valueOf('D'), new ItemStack(Items.DYE, 1, 0)});
            GameRegistry.addRecipe(new ItemStack(ModDyeArmor.black_boots, 1), new Object[]{"D D", "D D", Character.valueOf('D'), new ItemStack(Items.DYE, 1, 0)});
            GameRegistry.addRecipe(new ItemStack(ModDyeArmor.red_helmet, 1), new Object[]{"DDD", "D D", Character.valueOf('D'), new ItemStack(Items.DYE, 1, 1)});
            GameRegistry.addRecipe(new ItemStack(ModDyeArmor.red_chestplate, 1), new Object[]{"D D", "DDD", "DDD", Character.valueOf('D'), new ItemStack(Items.DYE, 1, 1)});
            GameRegistry.addRecipe(new ItemStack(ModDyeArmor.red_leggings, 1), new Object[]{"DDD", "D D", "D D", Character.valueOf('D'), new ItemStack(Items.DYE, 1, 1)});
            GameRegistry.addRecipe(new ItemStack(ModDyeArmor.red_boots, 1), new Object[]{"D D", "D D", Character.valueOf('D'), new ItemStack(Items.DYE, 1, 1)});
            GameRegistry.addRecipe(new ItemStack(ModDyeArmor.green_helmet, 1), new Object[]{"DDD", "D D", Character.valueOf('D'), new ItemStack(Items.DYE, 1, 2)});
            GameRegistry.addRecipe(new ItemStack(ModDyeArmor.green_chestplate, 1), new Object[]{"D D", "DDD", "DDD", Character.valueOf('D'), new ItemStack(Items.DYE, 1, 2)});
            GameRegistry.addRecipe(new ItemStack(ModDyeArmor.green_leggings, 1), new Object[]{"DDD", "D D", "D D", Character.valueOf('D'), new ItemStack(Items.DYE, 1, 2)});
            GameRegistry.addRecipe(new ItemStack(ModDyeArmor.green_boots, 1), new Object[]{"D D", "D D", Character.valueOf('D'), new ItemStack(Items.DYE, 1, 2)});
            GameRegistry.addRecipe(new ItemStack(ModDyeArmor.brown_helmet, 1), new Object[]{"DDD", "D D", Character.valueOf('D'), new ItemStack(Items.DYE, 1, 3)});
            GameRegistry.addRecipe(new ItemStack(ModDyeArmor.brown_chestplate, 1), new Object[]{"D D", "DDD", "DDD", Character.valueOf('D'), new ItemStack(Items.DYE, 1, 3)});
            GameRegistry.addRecipe(new ItemStack(ModDyeArmor.brown_leggings, 1), new Object[]{"DDD", "D D", "D D", Character.valueOf('D'), new ItemStack(Items.DYE, 1, 3)});
            GameRegistry.addRecipe(new ItemStack(ModDyeArmor.brown_boots, 1), new Object[]{"D D", "D D", Character.valueOf('D'), new ItemStack(Items.DYE, 1, 3)});
            GameRegistry.addRecipe(new ItemStack(ModDyeArmor.lapis_helmet, 1), new Object[]{"DDD", "D D", Character.valueOf('D'), new ItemStack(Items.DYE, 1, 4)});
            GameRegistry.addRecipe(new ItemStack(ModDyeArmor.lapis_chestplate, 1), new Object[]{"D D", "DDD", "DDD", Character.valueOf('D'), new ItemStack(Items.DYE, 1, 4)});
            GameRegistry.addRecipe(new ItemStack(ModDyeArmor.lapis_leggings, 1), new Object[]{"DDD", "D D", "D D", Character.valueOf('D'), new ItemStack(Items.DYE, 1, 4)});
            GameRegistry.addRecipe(new ItemStack(ModDyeArmor.lapis_boots, 1), new Object[]{"D D", "D D", Character.valueOf('D'), new ItemStack(Items.DYE, 1, 4)});
            GameRegistry.addRecipe(new ItemStack(ModDyeArmor.purple_helmet, 1), new Object[]{"DDD", "D D", Character.valueOf('D'), new ItemStack(Items.DYE, 1, 5)});
            GameRegistry.addRecipe(new ItemStack(ModDyeArmor.purple_chestplate, 1), new Object[]{"D D", "DDD", "DDD", Character.valueOf('D'), new ItemStack(Items.DYE, 1, 5)});
            GameRegistry.addRecipe(new ItemStack(ModDyeArmor.purple_leggings, 1), new Object[]{"DDD", "D D", "D D", Character.valueOf('D'), new ItemStack(Items.DYE, 1, 5)});
            GameRegistry.addRecipe(new ItemStack(ModDyeArmor.purple_boots, 1), new Object[]{"D D", "D D", Character.valueOf('D'), new ItemStack(Items.DYE, 1, 5)});
            GameRegistry.addRecipe(new ItemStack(ModDyeArmor.cyan_helmet, 1), new Object[]{"DDD", "D D", Character.valueOf('D'), new ItemStack(Items.DYE, 1, 6)});
            GameRegistry.addRecipe(new ItemStack(ModDyeArmor.cyan_chestplate, 1), new Object[]{"D D", "DDD", "DDD", Character.valueOf('D'), new ItemStack(Items.DYE, 1, 6)});
            GameRegistry.addRecipe(new ItemStack(ModDyeArmor.cyan_leggings, 1), new Object[]{"DDD", "D D", "D D", Character.valueOf('D'), new ItemStack(Items.DYE, 1, 6)});
            GameRegistry.addRecipe(new ItemStack(ModDyeArmor.cyan_boots, 1), new Object[]{"D D", "D D", Character.valueOf('D'), new ItemStack(Items.DYE, 1, 6)});
            GameRegistry.addRecipe(new ItemStack(ModDyeArmor.light_gray_helmet, 1), new Object[]{"DDD", "D D", Character.valueOf('D'), new ItemStack(Items.DYE, 1, 7)});
            GameRegistry.addRecipe(new ItemStack(ModDyeArmor.light_gray_chestplate, 1), new Object[]{"D D", "DDD", "DDD", Character.valueOf('D'), new ItemStack(Items.DYE, 1, 7)});
            GameRegistry.addRecipe(new ItemStack(ModDyeArmor.light_gray_leggings, 1), new Object[]{"DDD", "D D", "D D", Character.valueOf('D'), new ItemStack(Items.DYE, 1, 7)});
            GameRegistry.addRecipe(new ItemStack(ModDyeArmor.light_gray_boots, 1), new Object[]{"D D", "D D", Character.valueOf('D'), new ItemStack(Items.DYE, 1, 7)});
            GameRegistry.addRecipe(new ItemStack(ModDyeArmor.gray_helmet, 1), new Object[]{"DDD", "D D", Character.valueOf('D'), new ItemStack(Items.DYE, 1, 8)});
            GameRegistry.addRecipe(new ItemStack(ModDyeArmor.gray_chestplate, 1), new Object[]{"D D", "DDD", "DDD", Character.valueOf('D'), new ItemStack(Items.DYE, 1, 8)});
            GameRegistry.addRecipe(new ItemStack(ModDyeArmor.gray_leggings, 1), new Object[]{"DDD", "D D", "D D", Character.valueOf('D'), new ItemStack(Items.DYE, 1, 8)});
            GameRegistry.addRecipe(new ItemStack(ModDyeArmor.gray_boots, 1), new Object[]{"D D", "D D", Character.valueOf('D'), new ItemStack(Items.DYE, 1, 8)});
            GameRegistry.addRecipe(new ItemStack(ModDyeArmor.pink_helmet, 1), new Object[]{"DDD", "D D", Character.valueOf('D'), new ItemStack(Items.DYE, 1, 9)});
            GameRegistry.addRecipe(new ItemStack(ModDyeArmor.pink_chestplate, 1), new Object[]{"D D", "DDD", "DDD", Character.valueOf('D'), new ItemStack(Items.DYE, 1, 9)});
            GameRegistry.addRecipe(new ItemStack(ModDyeArmor.pink_leggings, 1), new Object[]{"DDD", "D D", "D D", Character.valueOf('D'), new ItemStack(Items.DYE, 1, 9)});
            GameRegistry.addRecipe(new ItemStack(ModDyeArmor.pink_boots, 1), new Object[]{"D D", "D D", Character.valueOf('D'), new ItemStack(Items.DYE, 1, 9)});
            GameRegistry.addRecipe(new ItemStack(ModDyeArmor.lime_helmet, 1), new Object[]{"DDD", "D D", Character.valueOf('D'), new ItemStack(Items.DYE, 1, 10)});
            GameRegistry.addRecipe(new ItemStack(ModDyeArmor.lime_chestplate, 1), new Object[]{"D D", "DDD", "DDD", Character.valueOf('D'), new ItemStack(Items.DYE, 1, 10)});
            GameRegistry.addRecipe(new ItemStack(ModDyeArmor.lime_leggings, 1), new Object[]{"DDD", "D D", "D D", Character.valueOf('D'), new ItemStack(Items.DYE, 1, 10)});
            GameRegistry.addRecipe(new ItemStack(ModDyeArmor.lime_boots, 1), new Object[]{"D D", "D D", Character.valueOf('D'), new ItemStack(Items.DYE, 1, 10)});
            GameRegistry.addRecipe(new ItemStack(ModDyeArmor.yellow_helmet, 1), new Object[]{"DDD", "D D", Character.valueOf('D'), new ItemStack(Items.DYE, 1, 11)});
            GameRegistry.addRecipe(new ItemStack(ModDyeArmor.yellow_chestplate, 1), new Object[]{"D D", "DDD", "DDD", Character.valueOf('D'), new ItemStack(Items.DYE, 1, 11)});
            GameRegistry.addRecipe(new ItemStack(ModDyeArmor.yellow_leggings, 1), new Object[]{"DDD", "D D", "D D", Character.valueOf('D'), new ItemStack(Items.DYE, 1, 11)});
            GameRegistry.addRecipe(new ItemStack(ModDyeArmor.yellow_boots, 1), new Object[]{"D D", "D D", Character.valueOf('D'), new ItemStack(Items.DYE, 1, 11)});
            GameRegistry.addRecipe(new ItemStack(ModDyeArmor.light_blue_helmet, 1), new Object[]{"DDD", "D D", Character.valueOf('D'), new ItemStack(Items.DYE, 1, 12)});
            GameRegistry.addRecipe(new ItemStack(ModDyeArmor.light_blue_chestplate, 1), new Object[]{"D D", "DDD", "DDD", Character.valueOf('D'), new ItemStack(Items.DYE, 1, 12)});
            GameRegistry.addRecipe(new ItemStack(ModDyeArmor.light_blue_leggings, 1), new Object[]{"DDD", "D D", "D D", Character.valueOf('D'), new ItemStack(Items.DYE, 1, 12)});
            GameRegistry.addRecipe(new ItemStack(ModDyeArmor.light_blue_boots, 1), new Object[]{"D D", "D D", Character.valueOf('D'), new ItemStack(Items.DYE, 1, 12)});
            GameRegistry.addRecipe(new ItemStack(ModDyeArmor.magenta_helmet, 1), new Object[]{"DDD", "D D", Character.valueOf('D'), new ItemStack(Items.DYE, 1, 13)});
            GameRegistry.addRecipe(new ItemStack(ModDyeArmor.magenta_chestplate, 1), new Object[]{"D D", "DDD", "DDD", Character.valueOf('D'), new ItemStack(Items.DYE, 1, 13)});
            GameRegistry.addRecipe(new ItemStack(ModDyeArmor.magenta_leggings, 1), new Object[]{"DDD", "D D", "D D", Character.valueOf('D'), new ItemStack(Items.DYE, 1, 13)});
            GameRegistry.addRecipe(new ItemStack(ModDyeArmor.magenta_boots, 1), new Object[]{"D D", "D D", Character.valueOf('D'), new ItemStack(Items.DYE, 1, 13)});
            GameRegistry.addRecipe(new ItemStack(ModDyeArmor.orange_helmet, 1), new Object[]{"DDD", "D D", Character.valueOf('D'), new ItemStack(Items.DYE, 1, 14)});
            GameRegistry.addRecipe(new ItemStack(ModDyeArmor.orange_chestplate, 1), new Object[]{"D D", "DDD", "DDD", Character.valueOf('D'), new ItemStack(Items.DYE, 1, 14)});
            GameRegistry.addRecipe(new ItemStack(ModDyeArmor.orange_leggings, 1), new Object[]{"DDD", "D D", "D D", Character.valueOf('D'), new ItemStack(Items.DYE, 1, 14)});
            GameRegistry.addRecipe(new ItemStack(ModDyeArmor.orange_boots, 1), new Object[]{"D D", "D D", Character.valueOf('D'), new ItemStack(Items.DYE, 1, 14)});
            GameRegistry.addRecipe(new ItemStack(ModDyeArmor.white_helmet, 1), new Object[]{"DDD", "D D", Character.valueOf('D'), new ItemStack(Items.DYE, 1, 15)});
            GameRegistry.addRecipe(new ItemStack(ModDyeArmor.white_chestplate, 1), new Object[]{"D D", "DDD", "DDD", Character.valueOf('D'), new ItemStack(Items.DYE, 1, 15)});
            GameRegistry.addRecipe(new ItemStack(ModDyeArmor.white_leggings, 1), new Object[]{"DDD", "D D", "D D", Character.valueOf('D'), new ItemStack(Items.DYE, 1, 15)});
            GameRegistry.addRecipe(new ItemStack(ModDyeArmor.white_boots, 1), new Object[]{"D D", "D D", Character.valueOf('D'), new ItemStack(Items.DYE, 1, 15)});
            GameRegistry.addRecipe(new ItemStack(ModArmor.red_netherbrick_helmet, 1), new Object[]{"DDD", "D D", Character.valueOf('D'), Blocks.RED_NETHER_BRICK});
            GameRegistry.addRecipe(new ItemStack(ModArmor.red_netherbrick_chestplate, 1), new Object[]{"D D", "DDD", "DDD", Character.valueOf('D'), Blocks.RED_NETHER_BRICK});
            GameRegistry.addRecipe(new ItemStack(ModArmor.red_netherbrick_leggings, 1), new Object[]{"DDD", "D D", "D D", Character.valueOf('D'), Blocks.RED_NETHER_BRICK});
            GameRegistry.addRecipe(new ItemStack(ModArmor.red_netherbrick_boots, 1), new Object[]{"D D", "D D", Character.valueOf('D'), Blocks.RED_NETHER_BRICK});

        }

        if (ConfigPreInit.disableBlocks) {
            GameRegistry.addRecipe(new ItemStack(ModBlocks.dye_black_block, 1), new Object[]{"BBB", "BBB", "BBB", Character.valueOf('B'), new ItemStack(Items.DYE, 1, 0)});
            GameRegistry.addRecipe(new ItemStack(ModBlocks.dye_red_block, 1), new Object[]{"BBB", "BBB", "BBB", Character.valueOf('B'), new ItemStack(Items.DYE, 1, 1)});
            GameRegistry.addRecipe(new ItemStack(ModBlocks.dye_green_block, 1), new Object[]{"BBB", "BBB", "BBB", Character.valueOf('B'), new ItemStack(Items.DYE, 1, 2)});
            GameRegistry.addRecipe(new ItemStack(ModBlocks.dye_brown_block, 1), new Object[]{"BBB", "BBB", "BBB", Character.valueOf('B'), new ItemStack(Items.DYE, 1, 3)});
            GameRegistry.addRecipe(new ItemStack(ModBlocks.dye_purple_block, 1), new Object[]{"BBB", "BBB", "BBB", Character.valueOf('B'), new ItemStack(Items.DYE, 1, 5)});
            GameRegistry.addRecipe(new ItemStack(ModBlocks.dye_cyan_block, 1), new Object[]{"BBB", "BBB", "BBB", Character.valueOf('B'), new ItemStack(Items.DYE, 1, 6)});
            GameRegistry.addRecipe(new ItemStack(ModBlocks.dye_silver_block, 1), new Object[]{"BBB", "BBB", "BBB", Character.valueOf('B'), new ItemStack(Items.DYE, 1, 7)});
            GameRegistry.addRecipe(new ItemStack(ModBlocks.dye_gray_block, 1), new Object[]{"BBB", "BBB", "BBB", Character.valueOf('B'), new ItemStack(Items.DYE, 1, 8)});
            GameRegistry.addRecipe(new ItemStack(ModBlocks.dye_pink_block, 1), new Object[]{"BBB", "BBB", "BBB", Character.valueOf('B'), new ItemStack(Items.DYE, 1, 9)});
            GameRegistry.addRecipe(new ItemStack(ModBlocks.dye_lime_block, 1), new Object[]{"BBB", "BBB", "BBB", Character.valueOf('B'), new ItemStack(Items.DYE, 1, 10)});
            GameRegistry.addRecipe(new ItemStack(ModBlocks.dye_yellow_block, 1), new Object[]{"BBB", "BBB", "BBB", Character.valueOf('B'), new ItemStack(Items.DYE, 1, 11)});
            GameRegistry.addRecipe(new ItemStack(ModBlocks.dye_light_blue_block, 1), new Object[]{"BBB", "BBB", "BBB", Character.valueOf('B'), new ItemStack(Items.DYE, 1, 12)});
            GameRegistry.addRecipe(new ItemStack(ModBlocks.dye_magenta_block, 1), new Object[]{"BBB", "BBB", "BBB", Character.valueOf('B'), new ItemStack(Items.DYE, 1, 13)});
            GameRegistry.addRecipe(new ItemStack(ModBlocks.dye_orange_block, 1), new Object[]{"BBB", "BBB", "BBB", Character.valueOf('B'), new ItemStack(Items.DYE, 1, 14)});
            GameRegistry.addRecipe(new ItemStack(ModBlocks.dye_white_block, 1), new Object[]{"BBB", "BBB", "BBB", Character.valueOf('B'), new ItemStack(Items.DYE, 1, 15)});

            GameRegistry.addRecipe(new ItemStack(ModBlocks.dye_black_stairs, 6), new Object[]{"B  ", "BB ", "BBB", Character.valueOf('B'), ModBlocks.dye_black_block});
            GameRegistry.addRecipe(new ItemStack(ModBlocks.dye_red_stairs, 6), new Object[]{"B  ", "BB ", "BBB", Character.valueOf('B'), ModBlocks.dye_red_block});
            GameRegistry.addRecipe(new ItemStack(ModBlocks.dye_green_stairs, 6), new Object[]{"B  ", "BB ", "BBB", Character.valueOf('B'), ModBlocks.dye_green_block});
            GameRegistry.addRecipe(new ItemStack(ModBlocks.dye_brown_stairs, 6), new Object[]{"B  ", "BB ", "BBB", Character.valueOf('B'), ModBlocks.dye_brown_block});
            GameRegistry.addRecipe(new ItemStack(ModBlocks.dye_blue_stairs, 6), new Object[]{"B  ", "BB ", "BBB", Character.valueOf('B'), Blocks.LAPIS_BLOCK});
            GameRegistry.addRecipe(new ItemStack(ModBlocks.dye_purple_stairs, 6), new Object[]{"B  ", "BB ", "BBB", Character.valueOf('B'), ModBlocks.dye_purple_block});
            GameRegistry.addRecipe(new ItemStack(ModBlocks.dye_cyan_stairs, 6), new Object[]{"B  ", "BB ", "BBB", Character.valueOf('B'), ModBlocks.dye_cyan_block});
            GameRegistry.addRecipe(new ItemStack(ModBlocks.dye_silver_stairs, 6), new Object[]{"B  ", "BB ", "BBB", Character.valueOf('B'), ModBlocks.dye_silver_block});
            GameRegistry.addRecipe(new ItemStack(ModBlocks.dye_gray_stairs, 6), new Object[]{"B  ", "BB ", "BBB", Character.valueOf('B'), ModBlocks.dye_gray_block});
            GameRegistry.addRecipe(new ItemStack(ModBlocks.dye_pink_stairs, 6), new Object[]{"B  ", "BB ", "BBB", Character.valueOf('B'), ModBlocks.dye_pink_block});
            GameRegistry.addRecipe(new ItemStack(ModBlocks.dye_lime_stairs, 6), new Object[]{"B  ", "BB ", "BBB", Character.valueOf('B'), ModBlocks.dye_lime_block});
            GameRegistry.addRecipe(new ItemStack(ModBlocks.dye_yellow_stairs, 6), new Object[]{"B  ", "BB ", "BBB", Character.valueOf('B'), ModBlocks.dye_yellow_block});
            GameRegistry.addRecipe(new ItemStack(ModBlocks.dye_light_blue_stairs, 6), new Object[]{"B  ", "BB ", "BBB", Character.valueOf('B'), ModBlocks.dye_light_blue_block});
            GameRegistry.addRecipe(new ItemStack(ModBlocks.dye_magenta_stairs, 6), new Object[]{"B  ", "BB ", "BBB", Character.valueOf('B'), ModBlocks.dye_magenta_block});
            GameRegistry.addRecipe(new ItemStack(ModBlocks.dye_orange_stairs, 6), new Object[]{"B  ", "BB ", "BBB", Character.valueOf('B'), ModBlocks.dye_orange_block});
            GameRegistry.addRecipe(new ItemStack(ModBlocks.dye_white_stairs, 6), new Object[]{"B  ", "BB ", "BBB", Character.valueOf('B'), ModBlocks.dye_white_block});


            GameRegistry.addRecipe(new ItemStack(ModBlocks.stonebrick_black, 8), new Object[]{"BBB", "BIB", "BBB", Character.valueOf('B'), Blocks.STONEBRICK, 'I', new ItemStack(Items.DYE, 1, 0)});
            GameRegistry.addRecipe(new ItemStack(ModBlocks.stonebrick_red, 8), new Object[]{"BBB", "BIB", "BBB", Character.valueOf('B'), Blocks.STONEBRICK, 'I', new ItemStack(Items.DYE, 1, 1)});
            GameRegistry.addRecipe(new ItemStack(ModBlocks.stonebrick_green, 8), new Object[]{"BBB", "BIB", "BBB", Character.valueOf('B'), Blocks.STONEBRICK, 'I', new ItemStack(Items.DYE, 1, 2)});
            GameRegistry.addRecipe(new ItemStack(ModBlocks.stonebrick_brown, 8), new Object[]{"BBB", "BIB", "BBB", Character.valueOf('B'), Blocks.STONEBRICK, 'I', new ItemStack(Items.DYE, 1, 3)});
            GameRegistry.addRecipe(new ItemStack(ModBlocks.stonebrick_blue, 8), new Object[]{"BBB", "BIB", "BBB", Character.valueOf('B'), Blocks.STONEBRICK, 'I', new ItemStack(Items.DYE, 1, 4)});
            GameRegistry.addRecipe(new ItemStack(ModBlocks.stonebrick_purple, 8), new Object[]{"BBB", "BIB", "BBB", Character.valueOf('B'), Blocks.STONEBRICK, 'I', new ItemStack(Items.DYE, 1, 5)});
            GameRegistry.addRecipe(new ItemStack(ModBlocks.stonebrick_cyan, 8), new Object[]{"BBB", "BIB", "BBB", Character.valueOf('B'), Blocks.STONEBRICK, 'I', new ItemStack(Items.DYE, 1, 6)});
            GameRegistry.addRecipe(new ItemStack(ModBlocks.stonebrick_silver, 8), new Object[]{"BBB", "BIB", "BBB", Character.valueOf('B'), Blocks.STONEBRICK, 'I', new ItemStack(Items.DYE, 1, 7)});
            GameRegistry.addRecipe(new ItemStack(ModBlocks.stonebrick_gray, 8), new Object[]{"BBB", "BIB", "BBB", Character.valueOf('B'), Blocks.STONEBRICK, 'I', new ItemStack(Items.DYE, 1, 8)});
            GameRegistry.addRecipe(new ItemStack(ModBlocks.stonebrick_pink, 8), new Object[]{"BBB", "BIB", "BBB", Character.valueOf('B'), Blocks.STONEBRICK, 'I', new ItemStack(Items.DYE, 1, 9)});
            GameRegistry.addRecipe(new ItemStack(ModBlocks.stonebrick_lime, 8), new Object[]{"BBB", "BIB", "BBB", Character.valueOf('B'), Blocks.STONEBRICK, 'I', new ItemStack(Items.DYE, 1, 10)});
            GameRegistry.addRecipe(new ItemStack(ModBlocks.stonebrick_yellow, 8), new Object[]{"BBB", "BIB", "BBB", Character.valueOf('B'), Blocks.STONEBRICK, 'I', new ItemStack(Items.DYE, 1, 11)});
            GameRegistry.addRecipe(new ItemStack(ModBlocks.stonebrick_light_blue, 8), new Object[]{"BBB", "BIB", "BBB", Character.valueOf('B'), Blocks.STONEBRICK, 'I', new ItemStack(Items.DYE, 1, 12)});
            GameRegistry.addRecipe(new ItemStack(ModBlocks.stonebrick_magenta, 8), new Object[]{"BBB", "BIB", "BBB", Character.valueOf('B'), Blocks.STONEBRICK, 'I', new ItemStack(Items.DYE, 1, 13)});
            GameRegistry.addRecipe(new ItemStack(ModBlocks.stonebrick_orange, 8), new Object[]{"BBB", "BIB", "BBB", Character.valueOf('B'), Blocks.STONEBRICK, 'I', new ItemStack(Items.DYE, 1, 14)});
            GameRegistry.addRecipe(new ItemStack(ModBlocks.stonebrick_white, 8), new Object[]{"BBB", "BIB", "BBB", Character.valueOf('B'), Blocks.STONEBRICK, 'I', new ItemStack(Items.DYE, 1, 15)});

            GameRegistry.addRecipe(new ItemStack(ModBlocks.stonebrick_black_stairs, 6), new Object[]{"B  ", "BB ", "BBB", Character.valueOf('B'), ModBlocks.stonebrick_black});
            GameRegistry.addRecipe(new ItemStack(ModBlocks.stonebrick_red_stairs, 6), new Object[]{"B  ", "BB ", "BBB", Character.valueOf('B'), ModBlocks.stonebrick_red});
            GameRegistry.addRecipe(new ItemStack(ModBlocks.stonebrick_green_stairs, 6), new Object[]{"B  ", "BB ", "BBB", Character.valueOf('B'), ModBlocks.stonebrick_green});
            GameRegistry.addRecipe(new ItemStack(ModBlocks.stonebrick_brown_stairs, 6), new Object[]{"B  ", "BB ", "BBB", Character.valueOf('B'), ModBlocks.stonebrick_brown});
            GameRegistry.addRecipe(new ItemStack(ModBlocks.stonebrick_blue_stairs, 6), new Object[]{"B  ", "BB ", "BBB", Character.valueOf('B'), ModBlocks.stonebrick_blue});
            GameRegistry.addRecipe(new ItemStack(ModBlocks.stonebrick_purple_stairs, 6), new Object[]{"B  ", "BB ", "BBB", Character.valueOf('B'), ModBlocks.stonebrick_purple});
            GameRegistry.addRecipe(new ItemStack(ModBlocks.stonebrick_cyan_stairs, 6), new Object[]{"B  ", "BB ", "BBB", Character.valueOf('B'), ModBlocks.stonebrick_cyan});
            GameRegistry.addRecipe(new ItemStack(ModBlocks.stonebrick_silver_stairs, 6), new Object[]{"B  ", "BB ", "BBB", Character.valueOf('B'), ModBlocks.stonebrick_silver});
            GameRegistry.addRecipe(new ItemStack(ModBlocks.stonebrick_gray_stairs, 6), new Object[]{"B  ", "BB ", "BBB", Character.valueOf('B'), ModBlocks.stonebrick_gray});
            GameRegistry.addRecipe(new ItemStack(ModBlocks.stonebrick_pink_stairs, 6), new Object[]{"B  ", "BB ", "BBB", Character.valueOf('B'), ModBlocks.stonebrick_pink});
            GameRegistry.addRecipe(new ItemStack(ModBlocks.stonebrick_lime_stairs, 6), new Object[]{"B  ", "BB ", "BBB", Character.valueOf('B'), ModBlocks.stonebrick_lime});
            GameRegistry.addRecipe(new ItemStack(ModBlocks.stonebrick_yellow_stairs, 6), new Object[]{"B  ", "BB ", "BBB", Character.valueOf('B'), ModBlocks.stonebrick_yellow});
            GameRegistry.addRecipe(new ItemStack(ModBlocks.stonebrick_light_blue_stairs, 6), new Object[]{"B  ", "BB ", "BBB", Character.valueOf('B'), ModBlocks.stonebrick_light_blue});
            GameRegistry.addRecipe(new ItemStack(ModBlocks.stonebrick_magenta_stairs, 6), new Object[]{"B  ", "BB ", "BBB", Character.valueOf('B'), ModBlocks.stonebrick_magenta});
            GameRegistry.addRecipe(new ItemStack(ModBlocks.stonebrick_orange_stairs, 6), new Object[]{"B  ", "BB ", "BBB", Character.valueOf('B'), ModBlocks.stonebrick_orange});
            GameRegistry.addRecipe(new ItemStack(ModBlocks.stonebrick_white_stairs, 6), new Object[]{"B  ", "BB ", "BBB", Character.valueOf('B'), ModBlocks.stonebrick_white});

        }
        if (ConfigPreInit.disableMiscItems) {

            GameRegistry.addRecipe(new ItemStack(ModRandomItems.inf_water_bucket, 1), new Object[]{"I I", 'I', Items.WATER_BUCKET});
            GameRegistry.addRecipe(new ItemStack(ModRandomItems.time_wand, 1), new Object[]{"C  ", " S ", "  S", 'C', Items.CLOCK, 'S', Items.STICK});

        }
        if (ConfigPreInit.disableFood) {
            GameRegistry.addSmelting(new ItemStack(Items.EGG, 1), new ItemStack(ModFood.fried_egg), 0);
            GameRegistry.addSmelting(new ItemStack(ModFood.bacon_raw, 1), new ItemStack(ModFood.bacon_cooked),0);
            GameRegistry.addRecipe(new ItemStack(ModFood.bacon_raw, 9), new Object[]{"P", "P", "P", 'P', Items.PORKCHOP});
            GameRegistry.addRecipe(new ItemStack(ModFood.baguette_roll, 1), new Object[]{"BBB", 'B', Items.BREAD});
            GameRegistry.addRecipe(new ItemStack(ModFood.baguette_bacon, 1), new Object[]{"RB", 'R', ModFood.baguette_roll, 'B',ModFood.bacon_cooked});
            GameRegistry.addRecipe(new ItemStack(ModFood.baguette_egg, 1), new Object[]{"RE", 'R', ModFood.baguette_roll, 'E',ModFood.fried_egg});
            GameRegistry.addRecipe(new ItemStack(ModFood.baguette_eggbacon, 1), new Object[]{"REB", 'R', ModFood.baguette_roll, 'E',ModFood.fried_egg, 'B', ModFood.bacon_cooked});
        }

        GameRegistry.addRecipe(new ItemStack(ModFurnaces.iron_furnace, 1), new Object[]{"III", "ISI", "III", 'I', Items.IRON_INGOT, 'S', Blocks.FURNACE});
        GameRegistry.addRecipe(new ItemStack(ModFurnaces.gold_furnace, 1), new Object[]{"GGG", "GIG", "GGG", 'G', Items.GOLD_INGOT, 'I', ModFurnaces.iron_furnace});
        GameRegistry.addRecipe(new ItemStack(ModFurnaces.diamond_furnace, 1), new Object[]{"DDD", "DGD", "DDD", 'D', Items.DIAMOND, 'G', ModFurnaces.gold_furnace});
        GameRegistry.addRecipe(new ItemStack(ModFurnaces.emerald_furnace, 1), new Object[]{"EEE", "EDE", "EEE", 'E', Items.EMERALD, 'D', ModFurnaces.diamond_furnace});
        GameRegistry.addShapelessRecipe(new ItemStack(ModPMS.obsidian_ingot, 9), new Object[]{Blocks.OBSIDIAN});
        GameRegistry.addRecipe(new ItemStack(Blocks.OBSIDIAN, 1), new Object[]{"OOO", "OOO", "OOO", 'O',ModPMS.obsidian_ingot});

        GameRegistry.addRecipe(new ItemStack(ModBlocks.cookie_jar_black, 1), new Object[]{" C ", "G G", "CCC", Character.valueOf('G'), new ItemStack(Item.getItemFromBlock(Blocks.STAINED_GLASS_PANE),1, 15), Character.valueOf('C'), new ItemStack(Item.getItemFromBlock(Blocks.STAINED_HARDENED_CLAY), 1, 15)});
        GameRegistry.addRecipe(new ItemStack(ModBlocks.cookie_jar_red, 1), new Object[]{" C ", "G G", "CCC", Character.valueOf('G'), new ItemStack(Item.getItemFromBlock(Blocks.STAINED_GLASS_PANE),1, 14), Character.valueOf('C'), new ItemStack(Item.getItemFromBlock(Blocks.STAINED_HARDENED_CLAY), 1, 14)});
        GameRegistry.addRecipe(new ItemStack(ModBlocks.cookie_jar_green, 1), new Object[]{" C ", "G G", "CCC", Character.valueOf('G'), new ItemStack(Item.getItemFromBlock(Blocks.STAINED_GLASS_PANE),1, 13), Character.valueOf('C'), new ItemStack(Item.getItemFromBlock(Blocks.STAINED_HARDENED_CLAY), 1, 13)});
        GameRegistry.addRecipe(new ItemStack(ModBlocks.cookie_jar_brown, 1), new Object[]{" C ", "G G", "CCC", Character.valueOf('G'), new ItemStack(Item.getItemFromBlock(Blocks.STAINED_GLASS_PANE),1, 12), Character.valueOf('C'), new ItemStack(Item.getItemFromBlock(Blocks.STAINED_HARDENED_CLAY), 1, 12)});
        GameRegistry.addRecipe(new ItemStack(ModBlocks.cookie_jar_blue, 1), new Object[]{" C ", "G G", "CCC", Character.valueOf('G'), new ItemStack(Item.getItemFromBlock(Blocks.STAINED_GLASS_PANE),1, 11), Character.valueOf('C'), new ItemStack(Item.getItemFromBlock(Blocks.STAINED_HARDENED_CLAY), 1, 11)});
        GameRegistry.addRecipe(new ItemStack(ModBlocks.cookie_jar_purple, 1), new Object[]{" C ", "G G", "CCC", Character.valueOf('G'), new ItemStack(Item.getItemFromBlock(Blocks.STAINED_GLASS_PANE),1, 10), Character.valueOf('C'), new ItemStack(Item.getItemFromBlock(Blocks.STAINED_HARDENED_CLAY), 1, 10)});
        GameRegistry.addRecipe(new ItemStack(ModBlocks.cookie_jar_cyan, 1), new Object[]{" C ", "G G", "CCC", Character.valueOf('G'), new ItemStack(Item.getItemFromBlock(Blocks.STAINED_GLASS_PANE),1, 9), Character.valueOf('C'), new ItemStack(Item.getItemFromBlock(Blocks.STAINED_HARDENED_CLAY), 1, 9)});
        GameRegistry.addRecipe(new ItemStack(ModBlocks.cookie_jar_silver, 1), new Object[]{" C ", "G G", "CCC", Character.valueOf('G'), new ItemStack(Item.getItemFromBlock(Blocks.STAINED_GLASS_PANE),1, 8), Character.valueOf('C'), new ItemStack(Item.getItemFromBlock(Blocks.STAINED_HARDENED_CLAY), 1, 8)});
        GameRegistry.addRecipe(new ItemStack(ModBlocks.cookie_jar_gray, 1), new Object[]{" C ", "G G", "CCC", Character.valueOf('G'), new ItemStack(Item.getItemFromBlock(Blocks.STAINED_GLASS_PANE),1, 7), Character.valueOf('C'), new ItemStack(Item.getItemFromBlock(Blocks.STAINED_HARDENED_CLAY), 1, 7)});
        GameRegistry.addRecipe(new ItemStack(ModBlocks.cookie_jar_pink, 1), new Object[]{" C ", "G G", "CCC", Character.valueOf('G'), new ItemStack(Item.getItemFromBlock(Blocks.STAINED_GLASS_PANE),1, 6), Character.valueOf('C'), new ItemStack(Item.getItemFromBlock(Blocks.STAINED_HARDENED_CLAY), 1, 6)});
        GameRegistry.addRecipe(new ItemStack(ModBlocks.cookie_jar_lime, 1), new Object[]{" C ", "G G", "CCC", Character.valueOf('G'), new ItemStack(Item.getItemFromBlock(Blocks.STAINED_GLASS_PANE),1, 5), Character.valueOf('C'), new ItemStack(Item.getItemFromBlock(Blocks.STAINED_HARDENED_CLAY), 1, 5)});
        GameRegistry.addRecipe(new ItemStack(ModBlocks.cookie_jar_yellow, 1), new Object[]{" C ", "G G", "CCC", Character.valueOf('G'), new ItemStack(Item.getItemFromBlock(Blocks.STAINED_GLASS_PANE),1, 4), Character.valueOf('C'), new ItemStack(Item.getItemFromBlock(Blocks.STAINED_HARDENED_CLAY), 1, 4)});
        GameRegistry.addRecipe(new ItemStack(ModBlocks.cookie_jar_light_blue, 1), new Object[]{" C ", "G G", "CCC", Character.valueOf('G'), new ItemStack(Item.getItemFromBlock(Blocks.STAINED_GLASS_PANE),1, 3), Character.valueOf('C'), new ItemStack(Item.getItemFromBlock(Blocks.STAINED_HARDENED_CLAY), 1, 3)});
        GameRegistry.addRecipe(new ItemStack(ModBlocks.cookie_jar_magenta, 1), new Object[]{" C ", "G G", "CCC", Character.valueOf('G'), new ItemStack(Item.getItemFromBlock(Blocks.STAINED_GLASS_PANE),1, 2), Character.valueOf('C'), new ItemStack(Item.getItemFromBlock(Blocks.STAINED_HARDENED_CLAY), 1, 2)});
        GameRegistry.addRecipe(new ItemStack(ModBlocks.cookie_jar_orange, 1), new Object[]{" C ", "G G", "CCC", Character.valueOf('G'), new ItemStack(Item.getItemFromBlock(Blocks.STAINED_GLASS_PANE),1, 1), Character.valueOf('C'), new ItemStack(Item.getItemFromBlock(Blocks.STAINED_HARDENED_CLAY), 1, 1)});
        GameRegistry.addRecipe(new ItemStack(ModBlocks.cookie_jar_white, 1), new Object[]{" C ", "G G", "CCC", Character.valueOf('G'), new ItemStack(Item.getItemFromBlock(Blocks.STAINED_GLASS_PANE),1, 0), Character.valueOf('C'), new ItemStack(Item.getItemFromBlock(Blocks.STAINED_HARDENED_CLAY), 1, 0)});

        GameRegistry.addRecipe(new ItemStack(ModBlocks.oak_storage_crate, 1), new Object[]{"OOO", "OCO", "OOO", Character.valueOf('C'), new ItemStack(Item.getItemFromBlock(Blocks.CHEST), 1, 0), Character.valueOf('O'), new ItemStack(Item.getItemFromBlock(Blocks.PLANKS), 1, 0)});
        GameRegistry.addRecipe(new ItemStack(ModBlocks.spruce_storage_crate, 1), new Object[]{"OOO", "OCO", "OOO", Character.valueOf('C'), new ItemStack(Item.getItemFromBlock(Blocks.CHEST),1,0), Character.valueOf('O'), new ItemStack(Item.getItemFromBlock(Blocks.PLANKS), 1, 1)});
        GameRegistry.addRecipe(new ItemStack(ModBlocks.birch_storage_crate, 1), new Object[]{"OOO", "OCO", "OOO", Character.valueOf('C'), new ItemStack(Item.getItemFromBlock(Blocks.CHEST),1,0), Character.valueOf('O'), new ItemStack(Item.getItemFromBlock(Blocks.PLANKS), 1, 2)});
        GameRegistry.addRecipe(new ItemStack(ModBlocks.jungle_storage_crate, 1), new Object[]{"OOO", "OCO", "OOO", Character.valueOf('C'), new ItemStack(Item.getItemFromBlock(Blocks.CHEST),1,0), Character.valueOf('O'), new ItemStack(Item.getItemFromBlock(Blocks.PLANKS), 1, 3)});
        GameRegistry.addRecipe(new ItemStack(ModBlocks.acacia_storage_crate, 1), new Object[]{"OOO", "OCO", "OOO", Character.valueOf('C'), new ItemStack(Item.getItemFromBlock(Blocks.CHEST),1,0), Character.valueOf('O'), new ItemStack(Item.getItemFromBlock(Blocks.PLANKS), 1, 4)});
        GameRegistry.addRecipe(new ItemStack(ModBlocks.big_oak_storage_crate, 1), new Object[]{"OOO", "OCO", "OOO", Character.valueOf('C'), new ItemStack(Item.getItemFromBlock(Blocks.CHEST),1,0), Character.valueOf('O'), new ItemStack(Item.getItemFromBlock(Blocks.PLANKS), 1, 5)});

        GameRegistry.addShapelessRecipe(new ItemStack(ModPMS.info_book, 1), new Object[]{Items.BOOK});

        if(ConfigPreInit.enableEndStoneRecipe) {
            GameRegistry.addRecipe(new ItemStack(Blocks.END_STONE, 1), new Object[]{" E ", "ESE", " E ", 'S', Blocks.SANDSTONE, 'E', Items.ENDER_PEARL});
        }

        if(ConfigPreInit.enableEndPortalFrameRecipe) {

            GameRegistry.addRecipe(new ItemStack(Blocks.END_PORTAL_FRAME, 1), new Object[]{"EOE", "SPS", "SSS", 'S', Blocks.END_STONE, 'E', Items.EMERALD, 'O', Blocks.OBSIDIAN, 'P', Items.ENDER_PEARL});
        }
    }
}
