package com.stc.pattysmorestuff.armor.init;

import com.stc.pattysmorestuff.lib.ConfigPreInit;
import com.stc.pattysmorestuff.armor.items.ItemMoreArmor;
import com.stc.pattysmorestuff.armor.items.ItemStarArmor;
import net.minecraft.client.renderer.block.model.ModelResourceLocation;
import net.minecraft.inventory.EntityEquipmentSlot;
import net.minecraft.item.Item;
import net.minecraftforge.client.model.ModelLoader;
import net.minecraftforge.fml.common.registry.GameRegistry;

/**
 * Created by StuffTheChicken on 13/11/2016.
 */
public class ModArmor {

    public static Item obsidian_helmet;
    public static Item obsidian_chestplate;
    public static Item obsidian_leggings;
    public static Item obsidian_boots;
    public static Item emerald_helmet;
    public static Item emerald_chestplate;
    public static Item emerald_leggings;
    public static Item emerald_boots;
    public static Item ender_helmet;
    public static Item ender_chestplate;
    public static Item ender_leggings;
    public static Item ender_boots;
    public static Item blaze_helmet;
    public static Item blaze_chestplate;
    public static Item blaze_leggings;
    public static Item blaze_boots;
    public static Item slime_helmet;
    public static Item slime_chestplate;
    public static Item slime_leggings;
    public static Item slime_boots;
    public static Item coal_helmet;
    public static Item coal_chestplate;
    public static Item coal_leggings;
    public static Item coal_boots;
    public static Item quartz_helmet;
    public static Item quartz_chestplate;
    public static Item quartz_leggings;
    public static Item quartz_boots;
    public static Item flint_helmet;
    public static Item flint_chestplate;
    public static Item flint_leggings;
    public static Item flint_boots;
    public static Item gunpowder_helmet;
    public static Item gunpowder_chestplate;
    public static Item gunpowder_leggings;
    public static Item gunpowder_boots;
    public static Item glowstone_helmet;
    public static Item glowstone_chestplate;
    public static Item glowstone_leggings;
    public static Item glowstone_boots;
    public static Item brick_helmet;
    public static Item brick_chestplate;
    public static Item brick_leggings;
    public static Item brick_boots;
    public static Item nether_brick_helmet;
    public static Item nether_brick_chestplate;
    public static Item nether_brick_leggings;
    public static Item nether_brick_boots;
    public static Item redstone_helmet;
    public static Item redstone_chestplate;
    public static Item redstone_leggings;
    public static Item redstone_boots;
    public static Item nether_star_helmet;
    public static Item nether_star_chestplate;
    public static Item nether_star_leggings;
    public static Item nether_star_boots;
    public static Item snow_helmet;
    public static Item snow_chestplate;
    public static Item snow_leggings;
    public static Item snow_boots;
    public static Item magma_cream_helmet;
    public static Item magma_cream_chestplate;
    public static Item magma_cream_leggings;
    public static Item magma_cream_boots;
    public static Item sandstone_helmet;
    public static Item sandstone_chestplate;
    public static Item sandstone_leggings;
    public static Item sandstone_boots;
    public static Item soul_sand_helmet;
    public static Item soul_sand_chestplate;
    public static Item soul_sand_leggings;
    public static Item soul_sand_boots;
    public static Item clay_helmet;
    public static Item clay_chestplate;
    public static Item clay_leggings;
    public static Item clay_boots;
    public static Item red_netherbrick_helmet;
    public static Item red_netherbrick_chestplate;
    public static Item red_netherbrick_leggings;
    public static Item red_netherbrick_boots;


    public static void init() {
        register(nether_star_helmet = new ItemStarArmor("nether_star_helmet", ConfigPreInit.NETHER_STAR_ARMOR, "nether_star", EntityEquipmentSlot.HEAD));
        register(nether_star_chestplate = new ItemStarArmor("nether_star_chestplate", ConfigPreInit.NETHER_STAR_ARMOR, "nether_star", EntityEquipmentSlot.CHEST));
        register(nether_star_leggings = new ItemStarArmor("nether_star_leggings", ConfigPreInit.NETHER_STAR_ARMOR, "nether_star", EntityEquipmentSlot.LEGS));
        register(nether_star_boots = new ItemStarArmor("nether_star_boots", ConfigPreInit.NETHER_STAR_ARMOR, "nether_star", EntityEquipmentSlot.FEET));
        register(obsidian_helmet = new ItemMoreArmor("obsidian_helmet", ConfigPreInit.OBSIDIAN_ARMOR, "obsidian", EntityEquipmentSlot.HEAD));
        register(obsidian_chestplate = new ItemMoreArmor("obsidian_chestplate", ConfigPreInit.OBSIDIAN_ARMOR, "obsidian", EntityEquipmentSlot.CHEST));
        register(obsidian_leggings = new ItemMoreArmor("obsidian_leggings", ConfigPreInit.OBSIDIAN_ARMOR, "obsidian", EntityEquipmentSlot.LEGS));
        register(obsidian_boots = new ItemMoreArmor("obsidian_boots", ConfigPreInit.OBSIDIAN_ARMOR, "obsidian", EntityEquipmentSlot.FEET));
        register(emerald_helmet = new ItemMoreArmor("emerald_helmet", ConfigPreInit.EMERALD_ARMOR, "emerald", EntityEquipmentSlot.HEAD));
        register(emerald_chestplate = new ItemMoreArmor("emerald_chestplate", ConfigPreInit.EMERALD_ARMOR, "emerald", EntityEquipmentSlot.CHEST));
        register(emerald_leggings = new ItemMoreArmor("emerald_leggings", ConfigPreInit.EMERALD_ARMOR, "emerald", EntityEquipmentSlot.LEGS));
        register(emerald_boots = new ItemMoreArmor("emerald_boots", ConfigPreInit.EMERALD_ARMOR, "emerald", EntityEquipmentSlot.FEET));
        register(ender_helmet = new ItemMoreArmor("ender_helmet", ConfigPreInit.ENDER_ARMOR, "ender", EntityEquipmentSlot.HEAD));
        register(ender_chestplate = new ItemMoreArmor("ender_chestplate", ConfigPreInit.ENDER_ARMOR, "ender", EntityEquipmentSlot.CHEST));
        register(ender_leggings = new ItemMoreArmor("ender_leggings", ConfigPreInit.ENDER_ARMOR, "ender", EntityEquipmentSlot.LEGS));
        register(ender_boots = new ItemMoreArmor("ender_boots", ConfigPreInit.ENDER_ARMOR, "ender", EntityEquipmentSlot.FEET));
        register(slime_helmet = new ItemMoreArmor("slime_helmet", ConfigPreInit.SLIME_ARMOR, "slime", EntityEquipmentSlot.HEAD));
        register(slime_chestplate = new ItemMoreArmor("slime_chestplate", ConfigPreInit.SLIME_ARMOR, "slime", EntityEquipmentSlot.CHEST));
        register(slime_leggings = new ItemMoreArmor("slime_leggings", ConfigPreInit.SLIME_ARMOR, "slime", EntityEquipmentSlot.LEGS));
        register(slime_boots = new ItemMoreArmor("slime_boots", ConfigPreInit.SLIME_ARMOR, "slime", EntityEquipmentSlot.FEET));
        register(magma_cream_helmet = new ItemMoreArmor("magma_cream_helmet", ConfigPreInit.MAGMA_CREAM_ARMOR, "magma_cream", EntityEquipmentSlot.HEAD));
        register(magma_cream_chestplate = new ItemMoreArmor("magma_cream_chestplate", ConfigPreInit.MAGMA_CREAM_ARMOR, "magma_cream", EntityEquipmentSlot.CHEST));
        register(magma_cream_leggings = new ItemMoreArmor("magma_cream_leggings", ConfigPreInit.MAGMA_CREAM_ARMOR, "magma_cream", EntityEquipmentSlot.LEGS));
        register(magma_cream_boots = new ItemMoreArmor("magma_cream_boots", ConfigPreInit.MAGMA_CREAM_ARMOR, "magma_cream", EntityEquipmentSlot.FEET));
        register(blaze_helmet = new ItemMoreArmor("blaze_helmet", ConfigPreInit.BLAZE_ARMOR, "blaze", EntityEquipmentSlot.HEAD));
        register(blaze_chestplate = new ItemMoreArmor("blaze_chestplate", ConfigPreInit.BLAZE_ARMOR, "blaze", EntityEquipmentSlot.CHEST));
        register(blaze_leggings = new ItemMoreArmor("blaze_leggings", ConfigPreInit.BLAZE_ARMOR, "blaze", EntityEquipmentSlot.LEGS));
        register(blaze_boots = new ItemMoreArmor("blaze_boots", ConfigPreInit.BLAZE_ARMOR, "blaze", EntityEquipmentSlot.FEET));
        register(glowstone_helmet = new ItemMoreArmor("glowstone_helmet", ConfigPreInit.GLOWSTONE_ARMOR, "glowstone", EntityEquipmentSlot.HEAD));
        register(glowstone_chestplate = new ItemMoreArmor("glowstone_chestplate", ConfigPreInit.GLOWSTONE_ARMOR, "glowstone", EntityEquipmentSlot.CHEST));
        register(glowstone_leggings = new ItemMoreArmor("glowstone_leggings", ConfigPreInit.GLOWSTONE_ARMOR, "glowstone", EntityEquipmentSlot.LEGS));
        register(glowstone_boots = new ItemMoreArmor("glowstone_boots", ConfigPreInit.GLOWSTONE_ARMOR, "glowstone", EntityEquipmentSlot.FEET));
        register(redstone_helmet = new ItemMoreArmor("redstone_helmet", ConfigPreInit.REDSTONE_ARMOR, "redstone", EntityEquipmentSlot.HEAD));
        register(redstone_chestplate = new ItemMoreArmor("redstone_chestplate", ConfigPreInit.REDSTONE_ARMOR, "redstone", EntityEquipmentSlot.CHEST));
        register(redstone_leggings = new ItemMoreArmor("redstone_leggings", ConfigPreInit.REDSTONE_ARMOR, "redstone", EntityEquipmentSlot.LEGS));
        register(redstone_boots = new ItemMoreArmor("redstone_boots", ConfigPreInit.REDSTONE_ARMOR, "redstone", EntityEquipmentSlot.FEET));
        register(quartz_helmet = new ItemMoreArmor("quartz_helmet", ConfigPreInit.QUARTZ_ARMOR, "quartz", EntityEquipmentSlot.HEAD));
        register(quartz_chestplate = new ItemMoreArmor("quartz_chestplate", ConfigPreInit.QUARTZ_ARMOR, "quartz", EntityEquipmentSlot.CHEST));
        register(quartz_leggings = new ItemMoreArmor("quartz_leggings", ConfigPreInit.QUARTZ_ARMOR, "quartz", EntityEquipmentSlot.LEGS));
        register(quartz_boots = new ItemMoreArmor("quartz_boots", ConfigPreInit.QUARTZ_ARMOR, "quartz", EntityEquipmentSlot.FEET));
        register(coal_helmet = new ItemMoreArmor("coal_helmet", ConfigPreInit.COAL_ARMOR, "coal", EntityEquipmentSlot.HEAD));
        register(coal_chestplate = new ItemMoreArmor("coal_chestplate", ConfigPreInit.COAL_ARMOR, "coal", EntityEquipmentSlot.CHEST));
        register(coal_leggings = new ItemMoreArmor("coal_leggings", ConfigPreInit.COAL_ARMOR, "coal", EntityEquipmentSlot.LEGS));
        register(coal_boots = new ItemMoreArmor("coal_boots", ConfigPreInit.COAL_ARMOR, "coal", EntityEquipmentSlot.FEET));
        register(flint_helmet = new ItemMoreArmor("flint_helmet", ConfigPreInit.FLINT_ARMOR, "flint", EntityEquipmentSlot.HEAD));
        register(flint_chestplate = new ItemMoreArmor("flint_chestplate", ConfigPreInit.FLINT_ARMOR, "flint", EntityEquipmentSlot.CHEST));
        register(flint_leggings = new ItemMoreArmor("flint_leggings", ConfigPreInit.FLINT_ARMOR, "flint", EntityEquipmentSlot.LEGS));
        register(flint_boots = new ItemMoreArmor("flint_boots", ConfigPreInit.FLINT_ARMOR, "flint", EntityEquipmentSlot.FEET));
        register(gunpowder_helmet = new ItemMoreArmor("gunpowder_helmet", ConfigPreInit.GUNPOWDER_ARMOR, "gunpowder", EntityEquipmentSlot.HEAD));
        register(gunpowder_chestplate = new ItemMoreArmor("gunpowder_chestplate", ConfigPreInit.GUNPOWDER_ARMOR, "gunpowder", EntityEquipmentSlot.CHEST));
        register(gunpowder_leggings = new ItemMoreArmor("gunpowder_leggings", ConfigPreInit.GUNPOWDER_ARMOR, "gunpowder", EntityEquipmentSlot.LEGS));
        register(gunpowder_boots = new ItemMoreArmor("gunpowder_boots", ConfigPreInit.GUNPOWDER_ARMOR, "gunpowder", EntityEquipmentSlot.FEET));
        register(brick_helmet = new ItemMoreArmor("brick_helmet", ConfigPreInit.BRICK_ARMOR, "brick", EntityEquipmentSlot.HEAD));
        register(brick_chestplate = new ItemMoreArmor("brick_chestplate", ConfigPreInit.BRICK_ARMOR, "brick", EntityEquipmentSlot.CHEST));
        register(brick_leggings = new ItemMoreArmor("brick_leggings", ConfigPreInit.BRICK_ARMOR, "brick", EntityEquipmentSlot.LEGS));
        register(brick_boots = new ItemMoreArmor("brick_boots", ConfigPreInit.BRICK_ARMOR, "brick", EntityEquipmentSlot.FEET));
        register(nether_brick_helmet = new ItemMoreArmor("nether_brick_helmet", ConfigPreInit.NETHER_BRICK_ARMOR, "nether_brick", EntityEquipmentSlot.HEAD));
        register(nether_brick_chestplate = new ItemMoreArmor("nether_brick_chestplate", ConfigPreInit.NETHER_BRICK_ARMOR, "nether_brick", EntityEquipmentSlot.CHEST));
        register(nether_brick_leggings = new ItemMoreArmor("nether_brick_leggings", ConfigPreInit.NETHER_BRICK_ARMOR, "nether_brick", EntityEquipmentSlot.LEGS));
        register(nether_brick_boots = new ItemMoreArmor("nether_brick_boots", ConfigPreInit.NETHER_BRICK_ARMOR, "nether_brick", EntityEquipmentSlot.FEET));
        register(sandstone_helmet = new ItemMoreArmor("sandstone_helmet", ConfigPreInit.SANDSTONE_ARMOR, "sandstone", EntityEquipmentSlot.HEAD));
        register(sandstone_chestplate = new ItemMoreArmor("sandstone_chestplate", ConfigPreInit.SANDSTONE_ARMOR, "sandstone", EntityEquipmentSlot.CHEST));
        register(sandstone_leggings = new ItemMoreArmor("sandstone_leggings", ConfigPreInit.SANDSTONE_ARMOR, "sandstone", EntityEquipmentSlot.LEGS));
        register(sandstone_boots = new ItemMoreArmor("sandstone_boots", ConfigPreInit.SANDSTONE_ARMOR, "sandstone", EntityEquipmentSlot.FEET));
        register(soul_sand_helmet = new ItemMoreArmor("soul_sand_helmet", ConfigPreInit.SOUL_SAND_ARMOR, "soul_sand", EntityEquipmentSlot.HEAD));
        register(soul_sand_chestplate = new ItemMoreArmor("soul_sand_chestplate", ConfigPreInit.SOUL_SAND_ARMOR, "soul_sand", EntityEquipmentSlot.CHEST));
        register(soul_sand_leggings = new ItemMoreArmor("soul_sand_leggings", ConfigPreInit.SOUL_SAND_ARMOR, "soul_sand", EntityEquipmentSlot.LEGS));
        register(soul_sand_boots = new ItemMoreArmor("soul_sand_boots", ConfigPreInit.SOUL_SAND_ARMOR, "soul_sand", EntityEquipmentSlot.FEET));
        register(snow_helmet = new ItemMoreArmor("snow_helmet", ConfigPreInit.SNOW_ARMOR, "snow", EntityEquipmentSlot.HEAD));
        register(snow_chestplate = new ItemMoreArmor("snow_chestplate", ConfigPreInit.SNOW_ARMOR, "snow", EntityEquipmentSlot.CHEST));
        register(snow_leggings = new ItemMoreArmor("snow_leggings", ConfigPreInit.SNOW_ARMOR, "snow", EntityEquipmentSlot.LEGS));
        register(snow_boots = new ItemMoreArmor("snow_boots", ConfigPreInit.SNOW_ARMOR, "snow", EntityEquipmentSlot.FEET));
        register(clay_helmet = new ItemMoreArmor("clay_helmet", ConfigPreInit.CLAY_ARMOR, "clay", EntityEquipmentSlot.HEAD));
        register(clay_chestplate = new ItemMoreArmor("clay_chestplate", ConfigPreInit.CLAY_ARMOR, "clay", EntityEquipmentSlot.CHEST));
        register(clay_leggings = new ItemMoreArmor("clay_leggings", ConfigPreInit.CLAY_ARMOR, "clay", EntityEquipmentSlot.LEGS));
        register(clay_boots = new ItemMoreArmor("clay_boots", ConfigPreInit.CLAY_ARMOR, "clay", EntityEquipmentSlot.FEET));
        register(red_netherbrick_helmet = new ItemMoreArmor("red_netherbrick_helmet", ConfigPreInit.RED_NETHER_BRICK_ARMOR, "red_nether_brick", EntityEquipmentSlot.HEAD));
        register(red_netherbrick_chestplate = new ItemMoreArmor("red_netherbrick_chestplate", ConfigPreInit.RED_NETHER_BRICK_ARMOR, "red_nether_brick", EntityEquipmentSlot.CHEST));
        register(red_netherbrick_leggings = new ItemMoreArmor("red_netherbrick_leggings", ConfigPreInit.RED_NETHER_BRICK_ARMOR, "red_nether_brick", EntityEquipmentSlot.LEGS));
        register(red_netherbrick_boots = new ItemMoreArmor("red_netherbrick_boots", ConfigPreInit.RED_NETHER_BRICK_ARMOR, "red_nether_brick", EntityEquipmentSlot.FEET));

    }

    public static void registerRender() {
        registerRenders(ModArmor.nether_star_helmet);
        registerRenders(ModArmor.nether_star_chestplate);
        registerRenders(ModArmor.nether_star_leggings);
        registerRenders(ModArmor.nether_star_boots);
        registerRenders(ModArmor.obsidian_helmet);
        registerRenders(ModArmor.obsidian_chestplate);
        registerRenders(ModArmor.obsidian_leggings);
        registerRenders(ModArmor.obsidian_boots);
        registerRenders(ModArmor.emerald_helmet);
        registerRenders(ModArmor.emerald_chestplate);
        registerRenders(ModArmor.emerald_leggings);
        registerRenders(ModArmor.emerald_boots);
        registerRenders(ModArmor.ender_helmet);
        registerRenders(ModArmor.ender_chestplate);
        registerRenders(ModArmor.ender_leggings);
        registerRenders(ModArmor.ender_boots);
        registerRenders(ModArmor.slime_helmet);
        registerRenders(ModArmor.slime_chestplate);
        registerRenders(ModArmor.slime_leggings);
        registerRenders(ModArmor.slime_boots);
        registerRenders(ModArmor.coal_helmet);
        registerRenders(ModArmor.coal_chestplate);
        registerRenders(ModArmor.coal_leggings);
        registerRenders(ModArmor.coal_boots);
        registerRenders(ModArmor.quartz_helmet);
        registerRenders(ModArmor.quartz_chestplate);
        registerRenders(ModArmor.quartz_leggings);
        registerRenders(ModArmor.quartz_boots);
        registerRenders(ModArmor.flint_helmet);
        registerRenders(ModArmor.flint_chestplate);
        registerRenders(ModArmor.flint_leggings);
        registerRenders(ModArmor.flint_boots);
        registerRenders(ModArmor.gunpowder_helmet);
        registerRenders(ModArmor.gunpowder_chestplate);
        registerRenders(ModArmor.gunpowder_leggings);
        registerRenders(ModArmor.gunpowder_boots);
        registerRenders(ModArmor.glowstone_helmet);
        registerRenders(ModArmor.glowstone_chestplate);
        registerRenders(ModArmor.glowstone_leggings);
        registerRenders(ModArmor.glowstone_boots);
        registerRenders(ModArmor.brick_helmet);
        registerRenders(ModArmor.brick_chestplate);
        registerRenders(ModArmor.brick_leggings);
        registerRenders(ModArmor.brick_boots);
        registerRenders(ModArmor.nether_brick_helmet);
        registerRenders(ModArmor.nether_brick_chestplate);
        registerRenders(ModArmor.nether_brick_leggings);
        registerRenders(ModArmor.nether_brick_boots);
        registerRenders(ModArmor.redstone_helmet);
        registerRenders(ModArmor.redstone_chestplate);
        registerRenders(ModArmor.redstone_leggings);
        registerRenders(ModArmor.redstone_boots);
        registerRenders(ModArmor.blaze_helmet);
        registerRenders(ModArmor.blaze_chestplate);
        registerRenders(ModArmor.blaze_leggings);
        registerRenders(ModArmor.blaze_boots);
        registerRenders(ModArmor.snow_helmet);
        registerRenders(ModArmor.snow_chestplate);
        registerRenders(ModArmor.snow_leggings);
        registerRenders(ModArmor.snow_boots);
        registerRenders(ModArmor.magma_cream_helmet);
        registerRenders(ModArmor.magma_cream_chestplate);
        registerRenders(ModArmor.magma_cream_leggings);
        registerRenders(ModArmor.magma_cream_boots);
        registerRenders(ModArmor.sandstone_helmet);
        registerRenders(ModArmor.sandstone_chestplate);
        registerRenders(ModArmor.sandstone_leggings);
        registerRenders(ModArmor.sandstone_boots);
        registerRenders(ModArmor.soul_sand_helmet);
        registerRenders(ModArmor.soul_sand_chestplate);
        registerRenders(ModArmor.soul_sand_leggings);
        registerRenders(ModArmor.soul_sand_boots);
        registerRenders(ModArmor.clay_helmet);
        registerRenders(ModArmor.clay_chestplate);
        registerRenders(ModArmor.clay_leggings);
        registerRenders(ModArmor.clay_boots);
        registerRenders(ModArmor.red_netherbrick_helmet);
        registerRenders(ModArmor.red_netherbrick_chestplate);
        registerRenders(ModArmor.red_netherbrick_leggings);
        registerRenders(ModArmor.red_netherbrick_boots);
    }


    private static <T extends Item> T register(T item) {
        GameRegistry.register(item);
        return item;
    }

    private static void registerRenders(Item item) {
        ModelResourceLocation modResLoc = new ModelResourceLocation(item.getRegistryName().toString(), "inventory");
        ModelLoader.setCustomModelResourceLocation(item, 0, modResLoc);
    }
}
