package com.stc.pattysmorestuff.armor.init;

import com.stc.pattysmorestuff.armor.items.ItemDyeArmor;
import com.stc.pattysmorestuff.ConfigPreInit;
import net.minecraft.client.renderer.block.model.ModelResourceLocation;
import net.minecraft.inventory.EntityEquipmentSlot;
import net.minecraft.item.Item;
import net.minecraftforge.client.model.ModelLoader;
import net.minecraftforge.fml.common.registry.GameRegistry;

/**
 * Created by peeweebirch70 on 13/11/2016.
 */
public class ModDyeArmor {
        public static Item black_helmet;
        public static Item black_chestplate;
        public static Item black_leggings;
        public static Item black_boots;
        public static Item red_helmet;
        public static Item red_chestplate;
        public static Item red_leggings;
        public static Item red_boots;
        public static Item green_helmet;
        public static Item green_chestplate;
        public static Item green_leggings;
        public static Item green_boots;
        public static Item brown_helmet;
        public static Item brown_chestplate;
        public static Item brown_leggings;
        public static Item brown_boots;
        public static Item lapis_helmet;
        public static Item lapis_chestplate;
        public static Item lapis_leggings;
        public static Item lapis_boots;
        public static Item purple_helmet;
        public static Item purple_chestplate;
        public static Item purple_leggings;
        public static Item purple_boots;
        public static Item cyan_helmet;
        public static Item cyan_chestplate;
        public static Item cyan_leggings;
        public static Item cyan_boots;
        public static Item light_gray_helmet;
        public static Item light_gray_chestplate;
        public static Item light_gray_leggings;
        public static Item light_gray_boots;
        public static Item gray_helmet;
        public static Item gray_chestplate;
        public static Item gray_leggings;
        public static Item gray_boots;
        public static Item pink_helmet;
        public static Item pink_chestplate;
        public static Item pink_leggings;
        public static Item pink_boots;
        public static Item lime_helmet;
        public static Item lime_chestplate;
        public static Item lime_leggings;
        public static Item lime_boots;
        public static Item yellow_helmet;
        public static Item yellow_chestplate;
        public static Item yellow_leggings;
        public static Item yellow_boots;
        public static Item light_blue_helmet;
        public static Item light_blue_chestplate;
        public static Item light_blue_leggings;
        public static Item light_blue_boots;
        public static Item magenta_helmet;
        public static Item magenta_chestplate;
        public static Item magenta_leggings;
        public static Item magenta_boots;
        public static Item orange_helmet;
        public static Item orange_chestplate;
        public static Item orange_leggings;
        public static Item orange_boots;
        public static Item white_helmet;
        public static Item white_chestplate;
        public static Item white_leggings;
        public static Item white_boots;

        public static void init() {
            register(black_helmet = new ItemDyeArmor("black_helmet", ConfigPreInit.DYE_ARMOR_BLACK, "black", EntityEquipmentSlot.HEAD), "black_helmet");
            register(black_chestplate = new ItemDyeArmor("black_chestplate", ConfigPreInit.DYE_ARMOR_BLACK, "black", EntityEquipmentSlot.CHEST), "black_chestplate");
            register(black_leggings = new ItemDyeArmor("black_leggings", ConfigPreInit.DYE_ARMOR_BLACK, "black", EntityEquipmentSlot.LEGS), "black_leggings");
            register(black_boots = new ItemDyeArmor("black_boots", ConfigPreInit.DYE_ARMOR_BLACK, "black", EntityEquipmentSlot.FEET), "black_boots");
            register(red_helmet = new ItemDyeArmor("red_helmet", ConfigPreInit.DYE_ARMOR_RED, "red", EntityEquipmentSlot.HEAD), "red_helmet");
            register(red_chestplate = new ItemDyeArmor("red_chestplate", ConfigPreInit.DYE_ARMOR_RED, "red", EntityEquipmentSlot.CHEST), "red_chestplate");
            register(red_leggings = new ItemDyeArmor("red_leggings", ConfigPreInit.DYE_ARMOR_RED, "red", EntityEquipmentSlot.LEGS), "red_leggings");
            register(red_boots = new ItemDyeArmor("red_boots", ConfigPreInit.DYE_ARMOR_RED, "red", EntityEquipmentSlot.FEET), "red_boots");
            register(green_helmet = new ItemDyeArmor("green_helmet", ConfigPreInit.DYE_ARMOR_GREEN, "green", EntityEquipmentSlot.HEAD), "green_helmet");
            register(green_chestplate = new ItemDyeArmor("green_chestplate", ConfigPreInit.DYE_ARMOR_GREEN, "green", EntityEquipmentSlot.CHEST), "green_chestplate");
            register(green_leggings = new ItemDyeArmor("green_leggings", ConfigPreInit.DYE_ARMOR_GREEN, "green", EntityEquipmentSlot.LEGS), "green_leggings");
            register(green_boots = new ItemDyeArmor("green_boots", ConfigPreInit.DYE_ARMOR_GREEN, "green", EntityEquipmentSlot.FEET), "green_boots");
            register(brown_helmet = new ItemDyeArmor("brown_helmet", ConfigPreInit.DYE_ARMOR_BROWN, "brown", EntityEquipmentSlot.HEAD), "brown_helmet");
            register(brown_chestplate = new ItemDyeArmor("brown_chestplate", ConfigPreInit.DYE_ARMOR_BROWN, "brown", EntityEquipmentSlot.CHEST), "brown_chestplate");
            register(brown_leggings = new ItemDyeArmor("brown_leggings", ConfigPreInit.DYE_ARMOR_BROWN, "brown", EntityEquipmentSlot.LEGS), "brown_leggings");
            register(brown_boots = new ItemDyeArmor("brown_boots", ConfigPreInit.DYE_ARMOR_BROWN, "brown", EntityEquipmentSlot.FEET), "brown_boots");
            register(lapis_helmet = new ItemDyeArmor("lapis_helmet", ConfigPreInit.DYE_ARMOR_BLUE, "lapis", EntityEquipmentSlot.HEAD), "lapis_helmet");
            register(lapis_chestplate = new ItemDyeArmor("lapis_chestplate", ConfigPreInit.DYE_ARMOR_BLUE, "lapis", EntityEquipmentSlot.CHEST), "lapis_chestplate");
            register(lapis_leggings = new ItemDyeArmor("lapis_leggings", ConfigPreInit.DYE_ARMOR_BLUE, "lapis", EntityEquipmentSlot.LEGS), "lapis_leggings");
            register(lapis_boots = new ItemDyeArmor("lapis_boots", ConfigPreInit.DYE_ARMOR_BLUE, "lapis", EntityEquipmentSlot.FEET), "lapis_boots");
            register(purple_helmet = new ItemDyeArmor("purple_helmet", ConfigPreInit.DYE_ARMOR_PURPLE, "purple", EntityEquipmentSlot.HEAD), "purple_helmet");
            register(purple_chestplate = new ItemDyeArmor("purple_chestplate", ConfigPreInit.DYE_ARMOR_PURPLE, "purple", EntityEquipmentSlot.CHEST), "purple_chestplate");
            register(purple_leggings = new ItemDyeArmor("purple_leggings", ConfigPreInit.DYE_ARMOR_PURPLE, "purple", EntityEquipmentSlot.LEGS), "purple_leggings");
            register(purple_boots = new ItemDyeArmor("purple_boots", ConfigPreInit.DYE_ARMOR_PURPLE, "purple", EntityEquipmentSlot.FEET), "purple_boots");
            register(cyan_helmet = new ItemDyeArmor("cyan_helmet", ConfigPreInit.DYE_ARMOR_CYAN, "cyan", EntityEquipmentSlot.HEAD), "cyan_helmet");
            register(cyan_chestplate = new ItemDyeArmor("cyan_chestplate", ConfigPreInit.DYE_ARMOR_CYAN, "cyan", EntityEquipmentSlot.CHEST), "cyan_chestplate");
            register(cyan_leggings = new ItemDyeArmor("cyan_leggings", ConfigPreInit.DYE_ARMOR_CYAN, "cyan", EntityEquipmentSlot.LEGS), "cyan_leggings");
            register(cyan_boots = new ItemDyeArmor("cyan_boots", ConfigPreInit.DYE_ARMOR_CYAN, "cyan", EntityEquipmentSlot.FEET), "cyan_boots");
            register(light_gray_helmet = new ItemDyeArmor("light_gray_helmet", ConfigPreInit.DYE_ARMOR_SILVER, "light_gray", EntityEquipmentSlot.HEAD), "light_gray_helmet");
            register(light_gray_chestplate = new ItemDyeArmor("light_gray_chestplate", ConfigPreInit.DYE_ARMOR_SILVER, "light_gray", EntityEquipmentSlot.CHEST), "light_gray_chestplate");
            register(light_gray_leggings = new ItemDyeArmor("light_gray_leggings", ConfigPreInit.DYE_ARMOR_SILVER, "light_gray", EntityEquipmentSlot.LEGS), "light_gray_leggings");
            register(light_gray_boots = new ItemDyeArmor("light_gray_boots", ConfigPreInit.DYE_ARMOR_SILVER, "light_gray", EntityEquipmentSlot.FEET), "light_gray_boots");
            register(gray_helmet = new ItemDyeArmor("gray_helmet", ConfigPreInit.DYE_ARMOR_GRAY, "gray", EntityEquipmentSlot.HEAD), "gray_helmet");
            register(gray_chestplate = new ItemDyeArmor("gray_chestplate", ConfigPreInit.DYE_ARMOR_GRAY, "gray", EntityEquipmentSlot.CHEST), "gray_chestplate");
            register(gray_leggings = new ItemDyeArmor("gray_leggings", ConfigPreInit.DYE_ARMOR_GRAY, "gray", EntityEquipmentSlot.LEGS), "gray_leggings");
            register(gray_boots = new ItemDyeArmor("gray_boots", ConfigPreInit.DYE_ARMOR_GRAY, "gray", EntityEquipmentSlot.FEET), "gray_boots");
            register(pink_helmet = new ItemDyeArmor("pink_helmet", ConfigPreInit.DYE_ARMOR_PINK, "pink", EntityEquipmentSlot.HEAD), "pink_helmet");
            register(pink_chestplate = new ItemDyeArmor("pink_chestplate", ConfigPreInit.DYE_ARMOR_PINK, "pink", EntityEquipmentSlot.CHEST), "pink_chestplate");
            register(pink_leggings = new ItemDyeArmor("pink_leggings", ConfigPreInit.DYE_ARMOR_PINK, "pink", EntityEquipmentSlot.LEGS), "pink_leggings");
            register(pink_boots = new ItemDyeArmor("pink_boots", ConfigPreInit.DYE_ARMOR_PINK, "pink", EntityEquipmentSlot.FEET), "pink_boots");
            register(lime_helmet = new ItemDyeArmor("lime_helmet", ConfigPreInit.DYE_ARMOR_LIME, "lime", EntityEquipmentSlot.HEAD), "lime_helmet");
            register(lime_chestplate = new ItemDyeArmor("lime_chestplate", ConfigPreInit.DYE_ARMOR_LIME, "lime", EntityEquipmentSlot.CHEST), "lime_chestplate");
            register(lime_leggings = new ItemDyeArmor("lime_leggings", ConfigPreInit.DYE_ARMOR_LIME, "lime", EntityEquipmentSlot.LEGS), "lime_leggings");
            register(lime_boots = new ItemDyeArmor("lime_boots", ConfigPreInit.DYE_ARMOR_LIME, "lime", EntityEquipmentSlot.FEET), "lime_boots");
            register(yellow_helmet = new ItemDyeArmor("yellow_helmet", ConfigPreInit.DYE_ARMOR_YELLOW, "yellow", EntityEquipmentSlot.HEAD), "yellow_helmet");
            register(yellow_chestplate = new ItemDyeArmor("yellow_chestplate", ConfigPreInit.DYE_ARMOR_YELLOW, "yellow", EntityEquipmentSlot.CHEST), "yellow_chestplate");
            register(yellow_leggings = new ItemDyeArmor("yellow_leggings", ConfigPreInit.DYE_ARMOR_YELLOW, "yellow", EntityEquipmentSlot.LEGS), "yellow_leggings");
            register(yellow_boots = new ItemDyeArmor("yellow_boots", ConfigPreInit.DYE_ARMOR_YELLOW, "yellow", EntityEquipmentSlot.FEET), "yellow_boots");
            register(light_blue_helmet = new ItemDyeArmor("light_blue_helmet", ConfigPreInit.DYE_ARMOR_LIGHT_BLUE, "light_blue", EntityEquipmentSlot.HEAD), "light_blue_helmet");
            register(light_blue_chestplate = new ItemDyeArmor("light_blue_chestplate", ConfigPreInit.DYE_ARMOR_LIGHT_BLUE, "light_blue", EntityEquipmentSlot.CHEST), "light_blue_chestplate");
            register(light_blue_leggings = new ItemDyeArmor("light_blue_leggings", ConfigPreInit.DYE_ARMOR_LIGHT_BLUE, "light_blue", EntityEquipmentSlot.LEGS), "light_blue_leggings");
            register(light_blue_boots = new ItemDyeArmor("light_blue_boots", ConfigPreInit.DYE_ARMOR_LIGHT_BLUE, "light_blue", EntityEquipmentSlot.FEET), "light_blue_boots");
            register(magenta_helmet = new ItemDyeArmor("magenta_helmet", ConfigPreInit.DYE_ARMOR_MAGENTA, "magenta", EntityEquipmentSlot.HEAD), "magenta_helmet");
            register(magenta_chestplate = new ItemDyeArmor("magenta_chestplate", ConfigPreInit.DYE_ARMOR_MAGENTA, "magenta", EntityEquipmentSlot.CHEST), "magenta_chestplate");
            register(magenta_leggings = new ItemDyeArmor("magenta_leggings", ConfigPreInit.DYE_ARMOR_MAGENTA, "magenta", EntityEquipmentSlot.LEGS), "magenta_leggings");
            register(magenta_boots = new ItemDyeArmor("magenta_boots", ConfigPreInit.DYE_ARMOR_MAGENTA, "magenta", EntityEquipmentSlot.FEET), "magenta_boots");
            register(orange_helmet = new ItemDyeArmor("orange_helmet", ConfigPreInit.DYE_ARMOR_ORANGE, "orange", EntityEquipmentSlot.HEAD), "orange_helmet");
            register(orange_chestplate = new ItemDyeArmor("orange_chestplate", ConfigPreInit.DYE_ARMOR_ORANGE, "orange", EntityEquipmentSlot.CHEST), "orange_chestplate");
            register(orange_leggings = new ItemDyeArmor("orange_leggings", ConfigPreInit.DYE_ARMOR_ORANGE, "orange", EntityEquipmentSlot.LEGS), "orange_leggings");
            register(orange_boots = new ItemDyeArmor("orange_boots", ConfigPreInit.DYE_ARMOR_ORANGE, "orange", EntityEquipmentSlot.FEET), "orange_boots");
            register(white_helmet = new ItemDyeArmor("white_helmet", ConfigPreInit.DYE_ARMOR_WHITE, "white", EntityEquipmentSlot.HEAD), "white_helmet");
            register(white_chestplate = new ItemDyeArmor("white_chestplate", ConfigPreInit.DYE_ARMOR_WHITE, "white", EntityEquipmentSlot.CHEST), "white_chestplate");
            register(white_leggings = new ItemDyeArmor("white_leggings", ConfigPreInit.DYE_ARMOR_WHITE, "white", EntityEquipmentSlot.LEGS), "white_leggings");
            register(white_boots = new ItemDyeArmor("white_boots", ConfigPreInit.DYE_ARMOR_WHITE, "white", EntityEquipmentSlot.FEET), "white_boots");

        }

    public static void registerRender() {
        registerRenders(ModDyeArmor.black_helmet);
        registerRenders(ModDyeArmor.black_chestplate);
        registerRenders(ModDyeArmor.black_leggings);
        registerRenders(ModDyeArmor.black_boots);
        registerRenders(ModDyeArmor.red_helmet);
        registerRenders(ModDyeArmor.red_chestplate);
        registerRenders(ModDyeArmor.red_leggings);
        registerRenders(ModDyeArmor.red_boots);
        registerRenders(ModDyeArmor.green_helmet);
        registerRenders(ModDyeArmor.green_chestplate);
        registerRenders(ModDyeArmor.green_leggings);
        registerRenders(ModDyeArmor.green_boots);
        registerRenders(ModDyeArmor.brown_helmet);
        registerRenders(ModDyeArmor.brown_chestplate);
        registerRenders(ModDyeArmor.brown_leggings);
        registerRenders(ModDyeArmor.brown_boots);
        registerRenders(ModDyeArmor.lapis_helmet);
        registerRenders(ModDyeArmor.lapis_chestplate);
        registerRenders(ModDyeArmor.lapis_leggings);
        registerRenders(ModDyeArmor.lapis_boots);
        registerRenders(ModDyeArmor.purple_helmet);
        registerRenders(ModDyeArmor.purple_chestplate);
        registerRenders(ModDyeArmor.purple_leggings);
        registerRenders(ModDyeArmor.purple_boots);
        registerRenders(ModDyeArmor.cyan_helmet);
        registerRenders(ModDyeArmor.cyan_chestplate);
        registerRenders(ModDyeArmor.cyan_leggings);
        registerRenders(ModDyeArmor.cyan_boots);
        registerRenders(ModDyeArmor.light_gray_helmet);
        registerRenders(ModDyeArmor.light_gray_chestplate);
        registerRenders(ModDyeArmor.light_gray_leggings);
        registerRenders(ModDyeArmor.light_gray_boots);
        registerRenders(ModDyeArmor.gray_helmet);
        registerRenders(ModDyeArmor.gray_chestplate);
        registerRenders(ModDyeArmor.gray_leggings);
        registerRenders(ModDyeArmor.gray_boots);
        registerRenders(ModDyeArmor.pink_helmet);
        registerRenders(ModDyeArmor.pink_chestplate);
        registerRenders(ModDyeArmor.pink_leggings);
        registerRenders(ModDyeArmor.pink_boots);
        registerRenders(ModDyeArmor.lime_helmet);
        registerRenders(ModDyeArmor.lime_chestplate);
        registerRenders(ModDyeArmor.lime_leggings);
        registerRenders(ModDyeArmor.lime_boots);
        registerRenders(ModDyeArmor.yellow_helmet);
        registerRenders(ModDyeArmor.yellow_chestplate);
        registerRenders(ModDyeArmor.yellow_leggings);
        registerRenders(ModDyeArmor.yellow_boots);
        registerRenders(ModDyeArmor.light_blue_helmet);
        registerRenders(ModDyeArmor.light_blue_chestplate);
        registerRenders(ModDyeArmor.light_blue_leggings);
        registerRenders(ModDyeArmor.light_blue_boots);
        registerRenders(ModDyeArmor.magenta_helmet);
        registerRenders(ModDyeArmor.magenta_chestplate);
        registerRenders(ModDyeArmor.magenta_leggings);
        registerRenders(ModDyeArmor.magenta_boots);
        registerRenders(ModDyeArmor.orange_helmet);
        registerRenders(ModDyeArmor.orange_chestplate);
        registerRenders(ModDyeArmor.orange_leggings);
        registerRenders(ModDyeArmor.orange_boots);
        registerRenders(ModDyeArmor.white_helmet);
        registerRenders(ModDyeArmor.white_chestplate);
        registerRenders(ModDyeArmor.white_leggings);
        registerRenders(ModDyeArmor.white_boots);

    }

        private static <T extends Item> T register(T item, String name) {
            GameRegistry.register(item);
            return item;
        }

        private static void registerRenders(Item item) {
            ModelResourceLocation modResLoc = new ModelResourceLocation(item.getRegistryName().toString(), "inventory");
            ModelLoader.setCustomModelResourceLocation(item, 0, modResLoc);
        }
}
